

insert into 
	yum.Balance_Sheet_Breakup
values
	(2018,'Assets','Current Assets','Prepaid expenses and other current assets','Income tax receivable',36)
	(2018,'Assets','Current Assets','Prepaid expenses and other current assets','Restricted cash',151),
	(2018,'Assets','Current Assets','Prepaid expenses and other current assets','Assets held for sale',24),
	(2018,'Assets','Current Assets','Prepaid expenses and other current assets','Other prepaid expenses and current assets',143),
	(2018,'Assets','Non-Current Assets','Property, plant and equipment (net)','Land',422),
	(2018,'Assets','Non-Current Assets','Property, plant and equipment (net)','Buildings and improvements',1349),
	(2018,'Assets','Non-Current Assets','Property, plant and equipment (net)','Capital leases, primarily buildings',59),
	(2018,'Assets','Non-Current Assets','Property, plant and equipment (net)','Machinery and equipment',523),
	(2018,'Assets','Non-Current Assets','Property, plant and equipment (net)','Accumulated depreciation and amortization',-1116),
	(2018,'Assets','Non-Current Assets','Other assets','Operating lease right-of-use assets',0),
	(2018,'Assets','Non-Current Assets','Other assets','Investment in Grubhub common stock',214),
	(2018,'Assets','Non-Current Assets','Other assets','Franchise incentives',141),
	(2018,'Assets','Non-Current Assets','Other assets','Investment in Devyani International Limited',0),
	(2018,'Assets','Non-Current Assets','Other assets','Other',369),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accounts payable',202),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued compensation and benefits',206),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued advertising',108),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Operating lease liabilities',0),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued taxes, other than income taxes',48),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Liabilities held for sale',0),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Other current liabilities',347),
	(2019,'Assets','Current Assets','Prepaid expenses and other current assets','Income tax receivable',39),
	(2019,'Assets','Current Assets','Prepaid expenses and other current assets','Restricted cash',138),
	(2019,'Assets','Current Assets','Prepaid expenses and other current assets','Assets held for sale',25),
	(2019,'Assets','Current Assets','Prepaid expenses and other current assets','Other prepaid expenses and current assets',136),
	(2019,'Assets','Non-Current Assets','Property, plant and equipment (net)','Land',408),
	(2019,'Assets','Non-Current Assets','Property, plant and equipment (net)','Buildings and improvements',1325),
	(2019,'Assets','Non-Current Assets','Property, plant and equipment (net)','Capital leases, primarily buildings',68),
	(2019,'Assets','Non-Current Assets','Property, plant and equipment (net)','Machinery and equipment',505),
	(2019,'Assets','Non-Current Assets','Property, plant and equipment (net)','Accumulated depreciation and amortization',-1136),
	(2019,'Assets','Non-Current Assets','Other assets','Operating lease right-of-use assets',642),
	(2019,'Assets','Non-Current Assets','Other assets','Investment in Grubhub common stock',137),
	(2019,'Assets','Non-Current Assets','Other assets','Franchise incentives',174),
	(2019,'Assets','Non-Current Assets','Other assets','Investment in Devyani International Limited',0),
	(2019,'Assets','Non-Current Assets','Other assets','Other',360),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accounts payable',173),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued compensation and benefits',223),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued advertising',96),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Operating lease liabilities',67),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued taxes, other than income taxes',52),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Liabilities held for sale',0),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Other current liabilities',349),
	(2020,'Assets','Current Assets','Prepaid expenses and other current assets','Income tax receivable',35),
	(2020,'Assets','Current Assets','Prepaid expenses and other current assets','Restricted cash',258),
	(2020,'Assets','Current Assets','Prepaid expenses and other current assets','Assets held for sale',7),
	(2020,'Assets','Current Assets','Prepaid expenses and other current assets','Other prepaid expenses and current assets',125),
	(2020,'Assets','Non-Current Assets','Property, plant and equipment (net)','Land',428),
	(2020,'Assets','Non-Current Assets','Property, plant and equipment (net)','Buildings and improvements',1423),
	(2020,'Assets','Non-Current Assets','Property, plant and equipment (net)','Capital leases, primarily buildings',71),
	(2020,'Assets','Non-Current Assets','Property, plant and equipment (net)','Machinery and equipment',543),
	(2020,'Assets','Non-Current Assets','Property, plant and equipment (net)','Accumulated depreciation and amortization',-1230),
	(2020,'Assets','Non-Current Assets','Other assets','Operating lease right-of-use assets',851),
	(2020,'Assets','Non-Current Assets','Other assets','Investment in Grubhub common stock',0),
	(2020,'Assets','Non-Current Assets','Other assets','Franchise incentives',163),
	(2020,'Assets','Non-Current Assets','Other assets','Investment in Devyani International Limited',0),
	(2020,'Assets','Non-Current Assets','Other assets','Other',421),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accounts payable',215),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued compensation and benefits',225),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued advertising',196),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Operating lease liabilities',97),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued taxes, other than income taxes',36),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Liabilities held for sale',0),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Other current liabilities',420),
	(2021,'Assets','Current Assets','Prepaid expenses and other current assets','Income tax receivable',50),
	(2021,'Assets','Current Assets','Prepaid expenses and other current assets','Restricted cash',250),
	(2021,'Assets','Current Assets','Prepaid expenses and other current assets','Assets held for sale',12),
	(2021,'Assets','Current Assets','Prepaid expenses and other current assets','Other prepaid expenses and current assets',138),
	(2021,'Assets','Non-Current Assets','Property, plant and equipment (net)','Land',412),
	(2021,'Assets','Non-Current Assets','Property, plant and equipment (net)','Buildings and improvements',1403),
	(2021,'Assets','Non-Current Assets','Property, plant and equipment (net)','Capital leases, primarily buildings',67),
	(2021,'Assets','Non-Current Assets','Property, plant and equipment (net)','Machinery and equipment',595),
	(2021,'Assets','Non-Current Assets','Property, plant and equipment (net)','Accumulated depreciation and amortization',-1270),
	(2021,'Assets','Non-Current Assets','Other assets','Operating lease right-of-use assets',809),
	(2021,'Assets','Non-Current Assets','Other assets','Investment in Grubhub common stock',0),
	(2021,'Assets','Non-Current Assets','Other assets','Franchise incentives',164),
	(2021,'Assets','Non-Current Assets','Other assets','Investment in Devyani International Limited',118),
	(2021,'Assets','Non-Current Assets','Other assets','Other',396),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accounts payable',227),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued compensation and benefits',292),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued advertising',229),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Operating lease liabilities',88),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued taxes, other than income taxes',78),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Liabilities held for sale',0),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Other current liabilities',420),
	(2022,'Assets','Current Assets','Prepaid expenses and other current assets','Income tax receivable',32),
	(2022,'Assets','Current Assets','Prepaid expenses and other current assets','Restricted cash',220),
	(2022,'Assets','Current Assets','Prepaid expenses and other current assets','Assets held for sale',190),
	(2022,'Assets','Current Assets','Prepaid expenses and other current assets','Other prepaid expenses and current assets',152),
	(2022,'Assets','Non-Current Assets','Property, plant and equipment (net)','Land',376),
	(2022,'Assets','Non-Current Assets','Property, plant and equipment (net)','Buildings and improvements',1364),
	(2022,'Assets','Non-Current Assets','Property, plant and equipment (net)','Capital leases, primarily buildings',63),
	(2022,'Assets','Non-Current Assets','Property, plant and equipment (net)','Machinery and equipment',651),
	(2022,'Assets','Non-Current Assets','Property, plant and equipment (net)','Accumulated depreciation and amortization',-1283),
	(2022,'Assets','Non-Current Assets','Other assets','Operating lease right-of-use assets',742),
	(2022,'Assets','Non-Current Assets','Other assets','Investment in Grubhub common stock',0),
	(2022,'Assets','Non-Current Assets','Other assets','Franchise incentives',172),
	(2022,'Assets','Non-Current Assets','Other assets','Investment in Devyani International Limited',116),
	(2022,'Assets','Non-Current Assets','Other assets','Other',294),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accounts payable',243),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued compensation and benefits',246),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued advertising',175),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Operating lease liabilities',79),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Accrued taxes, other than income taxes',83),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Liabilities held for sale',65),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities','Other current liabilities',360)

