



insert into 
	yum.Income_Consolidated
values
	(2018,'YUM Brands','Revenues ','Company sales','Q1',512),
	(2018,'YUM Brands','Revenues ','Franchise and property revenues','Q1',584),
	(2018,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q1',275),
	(2018,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q1',438),
	(2018,'YUM Brands','Costs and Expenses','General and administrative expenses','Q1',219),
	(2018,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q1',47),
	(2018,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q1',272),
	(2018,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q1',-156),
	(2018,'YUM Brands','Costs and Expenses','Other income/expense','Q1',-2),
	(2018,'YUM Brands','Interest Expense','Investment income/expense (net)','Q1',-66),
	(2018,'YUM Brands','Interest Expense','Other pension income/expense','Q1',3),
	(2018,'YUM Brands','Interest Expense','Interest expense (net)','Q1',107),
	(2018,'YUM Brands','Tax Expense','Income tax provision','Q1',76),
	(2019,'YUM Brands','Revenues ','Company sales','Q1',333),
	(2019,'YUM Brands','Revenues ','Franchise and property revenues','Q1',612),
	(2019,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q1',309),
	(2019,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q1',272),
	(2019,'YUM Brands','Costs and Expenses','General and administrative expenses','Q1',211),
	(2019,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q1',43),
	(2019,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q1',301),
	(2019,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q1',-6),
	(2019,'YUM Brands','Costs and Expenses','Other income/expense','Q1',0),
	(2019,'YUM Brands','Interest Expense','Investment income/expense (net)','Q1',16),
	(2019,'YUM Brands','Interest Expense','Other pension income/expense','Q1',3),
	(2019,'YUM Brands','Interest Expense','Interest expense (net)','Q1',115),
	(2019,'YUM Brands','Tax Expense','Income tax provision','Q1',37),
	(2020,'YUM Brands','Revenues ','Company sales','Q1',355),
	(2020,'YUM Brands','Revenues ','Franchise and property revenues','Q1',596),
	(2020,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q1',312),
	(2020,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q1',298),
	(2020,'YUM Brands','Costs and Expenses','General and administrative expenses','Q1',208),
	(2020,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q1',58),
	(2020,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q1',310),
	(2020,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q1',-13),
	(2020,'YUM Brands','Costs and Expenses','Other income/expense','Q1',152),
	(2020,'YUM Brands','Interest Expense','Investment income/expense (net)','Q1',34),
	(2020,'YUM Brands','Interest Expense','Other pension income/expense','Q1',3),
	(2020,'YUM Brands','Interest Expense','Interest expense (net)','Q1',118),
	(2020,'YUM Brands','Tax Expense','Income tax provision','Q1',12),
	(2021,'YUM Brands','Revenues ','Company sales','Q1',476),
	(2021,'YUM Brands','Revenues ','Franchise and property revenues','Q1',658),
	(2021,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q1',352),
	(2021,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q1',392),
	(2021,'YUM Brands','Costs and Expenses','General and administrative expenses','Q1',206),
	(2021,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q1',23),
	(2021,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q1',343),
	(2021,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q1',-15),
	(2021,'YUM Brands','Costs and Expenses','Other income/expense','Q1',-6),
	(2021,'YUM Brands','Interest Expense','Investment income/expense (net)','Q1',0),
	(2021,'YUM Brands','Interest Expense','Other pension income/expense','Q1',3),
	(2021,'YUM Brands','Interest Expense','Interest expense (net)','Q1',131),
	(2021,'YUM Brands','Tax Expense','Income tax provision','Q1',83),
	(2022,'YUM Brands','Revenues ','Company sales','Q1',470),
	(2022,'YUM Brands','Revenues ','Franchise and property revenues','Q1',714),
	(2022,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q1',363),
	(2022,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q1',402),
	(2022,'YUM Brands','Costs and Expenses','General and administrative expenses','Q1',253),
	(2022,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q1',32),
	(2022,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q1',361),
	(2022,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q1',-4),
	(2022,'YUM Brands','Costs and Expenses','Other income/expense','Q1',-6),
	(2022,'YUM Brands','Interest Expense','Investment income/expense (net)','Q1',-7),
	(2022,'YUM Brands','Interest Expense','Other pension income/expense','Q1',0),
	(2022,'YUM Brands','Interest Expense','Interest expense (net)','Q1',118),
	(2022,'YUM Brands','Tax Expense','Income tax provision','Q1',-1),
	(2023,'YUM Brands','Revenues ','Company sales','Q1',474),
	(2023,'YUM Brands','Revenues ','Franchise and property revenues','Q1',770),
	(2023,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q1',401),
	(2023,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q1',403),
	(2023,'YUM Brands','Costs and Expenses','General and administrative expenses','Q1',282),
	(2023,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q1',36),
	(2023,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q1',395),
	(2023,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q1',-4),
	(2023,'YUM Brands','Costs and Expenses','Other income/expense','Q1',10),
	(2023,'YUM Brands','Interest Expense','Investment income/expense (net)','Q1',24),
	(2023,'YUM Brands','Interest Expense','Other pension income/expense','Q1',-2),
	(2023,'YUM Brands','Interest Expense','Interest expense (net)','Q1',130),
	(2023,'YUM Brands','Tax Expense','Income tax provision','Q1',71),
	(2018,'YUM Brands','Revenues ','Company sales','Q2',512),
	(2018,'YUM Brands','Revenues ','Franchise and property revenues','Q2',584),
	(2018,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q2',272),
	(2018,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q2',421),
	(2018,'YUM Brands','Costs and Expenses','General and administrative expenses','Q2',208),
	(2018,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q2',40),
	(2018,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q2',274),
	(2018,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q2',-29),
	(2018,'YUM Brands','Costs and Expenses','Other income/expense','Q2',5),
	(2018,'YUM Brands','Interest Expense','Investment income/expense (net)','Q2',-23),
	(2018,'YUM Brands','Interest Expense','Other pension income/expense','Q2',3),
	(2018,'YUM Brands','Interest Expense','Interest expense (net)','Q2',112),
	(2018,'YUM Brands','Tax Expense','Income tax provision','Q2',36),
	(2019,'YUM Brands','Revenues ','Company sales','Q2',359),
	(2019,'YUM Brands','Revenues ','Franchise and property revenues','Q2',633),
	(2019,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q2',318),
	(2019,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q2',286),
	(2019,'YUM Brands','Costs and Expenses','General and administrative expenses','Q2',198),
	(2019,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q2',38),
	(2019,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q2',315),
	(2019,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q2',-4),
	(2019,'YUM Brands','Costs and Expenses','Other income/expense','Q2',6),
	(2019,'YUM Brands','Interest Expense','Investment income/expense (net)','Q2',-25),
	(2019,'YUM Brands','Interest Expense','Other pension income/expense','Q2',0),
	(2019,'YUM Brands','Interest Expense','Interest expense (net)','Q2',119),
	(2019,'YUM Brands','Tax Expense','Income tax provision','Q2',88),
	(2020,'YUM Brands','Revenues ','Company sales','Q2',403),
	(2020,'YUM Brands','Revenues ','Franchise and property revenues','Q2',525),
	(2020,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q2',270),
	(2020,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q2',349),
	(2020,'YUM Brands','Costs and Expenses','General and administrative expenses','Q2',259),
	(2020,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q2',36),
	(2020,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q2',264),
	(2020,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q2',-8),
	(2020,'YUM Brands','Costs and Expenses','Other income/expense','Q2',-2),
	(2020,'YUM Brands','Interest Expense','Investment income/expense (net)','Q2',-91),
	(2020,'YUM Brands','Interest Expense','Other pension income/expense','Q2',2),
	(2020,'YUM Brands','Interest Expense','Interest expense (net)','Q2',132),
	(2020,'YUM Brands','Tax Expense','Income tax provision','Q2',51),
	(2021,'YUM Brands','Revenues ','Company sales','Q2',520),
	(2021,'YUM Brands','Revenues ','Franchise and property revenues','Q2',706),
	(2021,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q2',376),
	(2021,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q2',417),
	(2021,'YUM Brands','Costs and Expenses','General and administrative expenses','Q2',230),
	(2021,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q2',27),
	(2021,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q2',372),
	(2021,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q2',-7),
	(2021,'YUM Brands','Costs and Expenses','Other income/expense','Q2',-4),
	(2021,'YUM Brands','Interest Expense','Investment income/expense (net)','Q2',-1),
	(2021,'YUM Brands','Interest Expense','Other pension income/expense','Q2',2),
	(2021,'YUM Brands','Interest Expense','Interest expense (net)','Q2',159),
	(2021,'YUM Brands','Tax Expense','Income tax provision','Q2',16),
	(2022,'YUM Brands','Revenues ','Company sales','Q2',499),
	(2022,'YUM Brands','Revenues ','Franchise and property revenues','Q2',737),
	(2022,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q2',400),
	(2022,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q2',415),
	(2022,'YUM Brands','Costs and Expenses','General and administrative expenses','Q2',254),
	(2022,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q2',29),
	(2022,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q2',396),
	(2022,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q2',-8),
	(2022,'YUM Brands','Costs and Expenses','Other income/expense','Q2',-4),
	(2022,'YUM Brands','Interest Expense','Investment income/expense (net)','Q2',15),
	(2022,'YUM Brands','Interest Expense','Other pension income/expense','Q2',1),
	(2022,'YUM Brands','Interest Expense','Interest expense (net)','Q2',148),
	(2022,'YUM Brands','Tax Expense','Income tax provision','Q2',166),
	(2023,'YUM Brands','Revenues ','Company sales','Q2',511),
	(2023,'YUM Brands','Revenues ','Franchise and property revenues','Q2',785),
	(2023,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q2',391),
	(2023,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q2',415),
	(2023,'YUM Brands','Costs and Expenses','General and administrative expenses','Q2',291),
	(2023,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q2',32),
	(2023,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q2',388),
	(2023,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q2',-17),
	(2023,'YUM Brands','Costs and Expenses','Other income/expense','Q2',5),
	(2023,'YUM Brands','Interest Expense','Investment income/expense (net)','Q2',-29),
	(2023,'YUM Brands','Interest Expense','Other pension income/expense','Q2',-1),
	(2023,'YUM Brands','Interest Expense','Interest expense (net)','Q2',125),
	(2023,'YUM Brands','Tax Expense','Income tax provision','Q2',60),
	(2018,'YUM Brands','Revenues ','Company sales','Q3',499),
	(2018,'YUM Brands','Revenues ','Franchise and property revenues','Q3',605),
	(2018,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q3',287),
	(2018,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q3',399),
	(2018,'YUM Brands','Costs and Expenses','General and administrative expenses','Q3',204),
	(2018,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q3',40),
	(2018,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q3',288),
	(2018,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q3',-100),
	(2018,'YUM Brands','Costs and Expenses','Other income/expense','Q3',7),
	(2018,'YUM Brands','Interest Expense','Investment income/expense (net)','Q3',-96),
	(2018,'YUM Brands','Interest Expense','Other pension income/expense','Q3',4),
	(2018,'YUM Brands','Interest Expense','Interest expense (net)','Q3',111),
	(2018,'YUM Brands','Tax Expense','Income tax provision','Q3',80),
	(2019,'YUM Brands','Revenues ','Company sales','Q3',364),
	(2019,'YUM Brands','Revenues ','Franchise and property revenues','Q3',645),
	(2019,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q3',330),
	(2019,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q3',292),
	(2019,'YUM Brands','Costs and Expenses','General and administrative expenses','Q3',208),
	(2019,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q3',43),
	(2019,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q3',325),
	(2019,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q3',-8),
	(2019,'YUM Brands','Costs and Expenses','Other income/expense','Q3',-1),
	(2019,'YUM Brands','Interest Expense','Investment income/expense (net)','Q3',59),
	(2019,'YUM Brands','Interest Expense','Other pension income/expense','Q3',1),
	(2019,'YUM Brands','Interest Expense','Interest expense (net)','Q3',120),
	(2019,'YUM Brands','Tax Expense','Income tax provision','Q3',45),
	(2020,'YUM Brands','Revenues ','Company sales','Q3',486),
	(2020,'YUM Brands','Revenues ','Franchise and property revenues','Q3',639),
	(2020,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q3',323),
	(2020,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q3',399),
	(2020,'YUM Brands','Costs and Expenses','General and administrative expenses','Q3',257),
	(2020,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q3',13),
	(2020,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q3',313),
	(2020,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q3',-9),
	(2020,'YUM Brands','Costs and Expenses','Other income/expense','Q3',4),
	(2020,'YUM Brands','Interest Expense','Investment income/expense (net)','Q3',-10),
	(2020,'YUM Brands','Interest Expense','Other pension income/expense','Q3',4),
	(2020,'YUM Brands','Interest Expense','Interest expense (net)','Q3',161),
	(2020,'YUM Brands','Tax Expense','Income tax provision','Q3',33),
	(2021,'YUM Brands','Revenues ','Company sales','Q3',513),
	(2021,'YUM Brands','Revenues ','Franchise and property revenues','Q3',716),
	(2021,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q3',377),
	(2021,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q3',421),
	(2021,'YUM Brands','Costs and Expenses','General and administrative expenses','Q3',253),
	(2021,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q3',31),
	(2021,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q3',375),
	(2021,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q3',1),
	(2021,'YUM Brands','Costs and Expenses','Other income/expense','Q3',-2),
	(2021,'YUM Brands','Interest Expense','Investment income/expense (net)','Q3',-51),
	(2021,'YUM Brands','Interest Expense','Other pension income/expense','Q3',1),
	(2021,'YUM Brands','Interest Expense','Interest expense (net)','Q3',126),
	(2021,'YUM Brands','Tax Expense','Income tax provision','Q3',-77),
	(2022,'YUM Brands','Revenues ','Company sales','Q3',479),
	(2022,'YUM Brands','Revenues ','Franchise and property revenues','Q3',760),
	(2022,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q3',401),
	(2022,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q3',402),
	(2022,'YUM Brands','Costs and Expenses','General and administrative expenses','Q3',261),
	(2022,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q3',28),
	(2022,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q3',396),
	(2022,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q3',-3),
	(2022,'YUM Brands','Costs and Expenses','Other income/expense','Q3',10),
	(2022,'YUM Brands','Interest Expense','Investment income/expense (net)','Q3',-27),
	(2022,'YUM Brands','Interest Expense','Other pension income/expense','Q3',2),
	(2022,'YUM Brands','Interest Expense','Interest expense (net)','Q3',124),
	(2022,'YUM Brands','Tax Expense','Income tax provision','Q3',116),
	(2023,'YUM Brands','Revenues ','Company sales','Q3',510),
	(2023,'YUM Brands','Revenues ','Franchise and property revenues','Q3',796),
	(2023,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q3',402),
	(2023,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q3',421),
	(2023,'YUM Brands','Costs and Expenses','General and administrative expenses','Q3',267),
	(2023,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q3',27),
	(2023,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q3',400),
	(2023,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q3',-19),
	(2023,'YUM Brands','Costs and Expenses','Other income/expense','Q3',-1),
	(2023,'YUM Brands','Interest Expense','Investment income/expense (net)','Q3',-16),
	(2023,'YUM Brands','Interest Expense','Other pension income/expense','Q3',-2),
	(2023,'YUM Brands','Interest Expense','Interest expense (net)','Q3',126),
	(2023,'YUM Brands','Tax Expense','Income tax provision','Q3',89),
	(2018,'YUM Brands','Revenues ','Company sales','Q4',477),
	(2018,'YUM Brands','Revenues ','Franchise and property revenues','Q4',709),
	(2018,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q4',372),
	(2018,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q4',376),
	(2018,'YUM Brands','Costs and Expenses','General and administrative expenses','Q4',264),
	(2018,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q4',61),
	(2018,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q4',374),
	(2018,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q4',-255),
	(2018,'YUM Brands','Costs and Expenses','Other income/expense','Q4',-3),
	(2018,'YUM Brands','Interest Expense','Investment income/expense (net)','Q4',176),
	(2018,'YUM Brands','Interest Expense','Other pension income/expense','Q4',4),
	(2018,'YUM Brands','Interest Expense','Interest expense (net)','Q4',122),
	(2018,'YUM Brands','Tax Expense','Income tax provision','Q4',105),
	(2019,'YUM Brands','Revenues ','Company sales','Q4',490),
	(2019,'YUM Brands','Revenues ','Franchise and property revenues','Q4',770),
	(2019,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q4',434),
	(2019,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q4',385),
	(2019,'YUM Brands','Costs and Expenses','General and administrative expenses','Q4',300),
	(2019,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q4',56),
	(2019,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q4',427),
	(2019,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q4',-19),
	(2019,'YUM Brands','Costs and Expenses','Other income/expense','Q4',-1),
	(2019,'YUM Brands','Interest Expense','Investment income/expense (net)','Q4',17),
	(2019,'YUM Brands','Interest Expense','Other pension income/expense','Q4',0),
	(2019,'YUM Brands','Interest Expense','Interest expense (net)','Q4',132),
	(2019,'YUM Brands','Tax Expense','Income tax provision','Q4',-91),
	(2020,'YUM Brands','Revenues ','Company sales','Q4',566),
	(2020,'YUM Brands','Revenues ','Franchise and property revenues','Q4',750),
	(2020,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q4',427),
	(2020,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q4',460),
	(2020,'YUM Brands','Costs and Expenses','General and administrative expenses','Q4',340),
	(2020,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q4',38),
	(2020,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q4',427),
	(2020,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q4',-4),
	(2020,'YUM Brands','Costs and Expenses','Other income/expense','Q4',0),
	(2020,'YUM Brands','Interest Expense','Investment income/expense (net)','Q4',-7),
	(2020,'YUM Brands','Interest Expense','Other pension income/expense','Q4',5),
	(2020,'YUM Brands','Interest Expense','Interest expense (net)','Q4',132),
	(2020,'YUM Brands','Tax Expense','Income tax provision','Q4',20),
	(2021,'YUM Brands','Revenues ','Company sales','Q4',597),
	(2021,'YUM Brands','Revenues ','Franchise and property revenues','Q4',820),
	(2021,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q4',473),
	(2021,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q4',495),
	(2021,'YUM Brands','Costs and Expenses','General and administrative expenses','Q4',371),
	(2021,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q4',36),
	(2021,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q4',486),
	(2021,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q4',-14),
	(2021,'YUM Brands','Costs and Expenses','Other income/expense','Q4',14),
	(2021,'YUM Brands','Interest Expense','Investment income/expense (net)','Q4',-34),
	(2021,'YUM Brands','Interest Expense','Other pension income/expense','Q4',1),
	(2021,'YUM Brands','Interest Expense','Interest expense (net)','Q4',128),
	(2021,'YUM Brands','Tax Expense','Income tax provision','Q4',77),
	(2022,'YUM Brands','Revenues ','Company sales','Q4',624),
	(2022,'YUM Brands','Revenues ','Franchise and property revenues','Q4',885),
	(2022,'YUM Brands','Revenues ','Franchise contributions for advertising and other services','Q4',510),
	(2022,'YUM Brands','Costs and Expenses','Company restaurant expenses','Q4',526),
	(2022,'YUM Brands','Costs and Expenses','General and administrative expenses','Q4',372),
	(2022,'YUM Brands','Costs and Expenses','Franchise and property expenses','Q4',34),
	(2022,'YUM Brands','Costs and Expenses','Franchise advertising and other services expense','Q4',514),
	(2022,'YUM Brands','Costs and Expenses','Refranchising gain/loss','Q4',-12),
	(2022,'YUM Brands','Costs and Expenses','Other income/expense','Q4',7),
	(2022,'YUM Brands','Interest Expense','Investment income/expense (net)','Q4',8),
	(2022,'YUM Brands','Interest Expense','Other pension income/expense','Q4',6),
	(2022,'YUM Brands','Interest Expense','Interest expense (net)','Q4',137),
	(2022,'YUM Brands','Tax Expense','Income tax provision','Q4',56)
