insert into yum.cashflow
values
	(2018,'Operating Activities','Net Income','Cash Inflow',1542),
	(2018,'Operating Activities','Income from discontinued operations (net tax)','Cash Inflow',0),
	(2018,'Operating Activities','Depreciation and amortization','Cash Inflow',137),
	(2018,'Operating Activities','Impairment and closure expense','Cash Inflow',0),
	(2018,'Operating Activities','Refranchising gain/loss','Cash Outflow',-540),
	(2018,'Operating Activities','Investment income/expense (net)','Cash Outflow',-9),
	(2018,'Operating Activities','Contributions to defined benefit pension plans','Cash Outflow',-16),
	(2018,'Operating Activities','Deferred income taxes','Cash Outflow',-11),
	(2018,'Operating Activities','Share-based compensation expense','Cash Inflow',50),
	(2018,'Operating Activities','Changes in accounts and notes receivable','Cash Outflow',-66),
	(2018,'Operating Activities','Changes in prepaid expenses and other current assets','Cash Inflow',0),
	(2018,'Operating Activities','Changes in accounts payable and other current liabilities','Cash Outflow',-68),
	(2018,'Operating Activities','Changes in income taxes payable','Cash Inflow',65),
	(2018,'Operating Activities','Other (net)','Cash Inflow',92),
	(2018,'Investing Activities','Capital spending','Cash Outflow',-234),
	(2018,'Investing Activities','QuikOrder acquisition, net of cash acquired','Cash Outflow',-66),
	(2018,'Investing Activities','Investment in Grubhub Inc. common stock','Cash Outflow',-200),
	(2018,'Investing Activities','Acquisition of The Habit Restaurants, Inc. (net cash)','Cash Inflow',0),
	(2018,'Investing Activities','Proceeds from sale/purchase of investment in Grubhub, Inc. (common stock)','Cash Inflow',0),
	(2018,'Investing Activities','Proceeds from sale of KFC Russia','Cash Inflow',0),
	(2018,'Investing Activities','Proceeds from refranchising of restaurants','Cash Inflow',825),
	(2018,'Investing Activities','Other (net)','Cash Outflow',-12),
	(2018,'Financing Activities','Proceeds from long-term debt','Cash Inflow',1556),
	(2018,'Financing Activities','Repayments of long-term debt','Cash Outflow',-1264),
	(2018,'Financing Activities','Revolving credit facilities, three months or less, net','Cash Inflow',0),
	(2018,'Financing Activities','Short-term borrowings - More than three months – proceeds','Cash Inflow',59),
	(2018,'Financing Activities','Short-term borrowings - More than three months – payments','Cash Outflow',-59),
	(2018,'Financing Activities','Short-term borrowings -Three months or less, net','Cash Inflow',0),
	(2018,'Financing Activities','Repurchase shares of Common Stock','Cash Outflow',-2390),
	(2018,'Financing Activities','Dividends paid on Common Stock','Cash Outflow',-462),
	(2018,'Financing Activities','Debt issuance costs','Cash Outflow',-13),
	(2018,'Financing Activities','Net transfers from discontinued operations','Cash Inflow',0),
	(2018,'Financing Activities','Other (net)','Cash Outflow',-47),
	(2019,'Operating Activities','Net Income','Cash Inflow',1294),
	(2019,'Operating Activities','Income from discontinued operations (net tax)','Cash Inflow',0),
	(2019,'Operating Activities','Depreciation and amortization','Cash Inflow',112),
	(2019,'Operating Activities','Impairment and closure expense','Cash Inflow',0),
	(2019,'Operating Activities','Refranchising gain/loss','Cash Outflow',-37),
	(2019,'Operating Activities','Investment income/expense (net)','Cash Inflow',67),
	(2019,'Operating Activities','Contributions to defined benefit pension plans','Cash Outflow',-15),
	(2019,'Operating Activities','Deferred income taxes','Cash Outflow',-232),
	(2019,'Operating Activities','Share-based compensation expense','Cash Inflow',59),
	(2019,'Operating Activities','Changes in accounts and notes receivable','Cash Outflow',-56),
	(2019,'Operating Activities','Changes in prepaid expenses and other current assets','Cash Outflow',-8),
	(2019,'Operating Activities','Changes in accounts payable and other current liabilities','Cash Outflow',-36),
	(2019,'Operating Activities','Changes in income taxes payable','Cash Inflow',23),
	(2019,'Operating Activities','Other (net)','Cash Inflow',144),
	(2019,'Investing Activities','Capital spending','Cash Outflow',-196),
	(2019,'Investing Activities','QuikOrder acquisition, net of cash acquired','Cash Inflow',0),
	(2019,'Investing Activities','Investment in Grubhub Inc. common stock','Cash Inflow',0),
	(2019,'Investing Activities','Acquisition of The Habit Restaurants, Inc. (net cash)','Cash Inflow',0),
	(2019,'Investing Activities','Proceeds from sale/purchase of investment in Grubhub, Inc. (common stock)','Cash Inflow',0),
	(2019,'Investing Activities','Proceeds from sale of KFC Russia','Cash Inflow',0),
	(2019,'Investing Activities','Proceeds from refranchising of restaurants','Cash Inflow',110),
	(2019,'Investing Activities','Other (net)','Cash Outflow',-2),
	(2019,'Financing Activities','Proceeds from long-term debt','Cash Inflow',800),
	(2019,'Financing Activities','Repayments of long-term debt','Cash Outflow',-331),
	(2019,'Financing Activities','Revolving credit facilities, three months or less, net','Cash Inflow',0),
	(2019,'Financing Activities','Short-term borrowings - More than three months – proceeds','Cash Inflow',130),
	(2019,'Financing Activities','Short-term borrowings - More than three months – payments','Cash Outflow',-126),
	(2019,'Financing Activities','Short-term borrowings -Three months or less, net','Cash Inflow',0),
	(2019,'Financing Activities','Repurchase shares of Common Stock','Cash Outflow',-815),
	(2019,'Financing Activities','Dividends paid on Common Stock','Cash Outflow',-511),
	(2019,'Financing Activities','Debt issuance costs','Cash Outflow',-10),
	(2019,'Financing Activities','Net transfers from discontinued operations','Cash Inflow',0),
	(2019,'Financing Activities','Other (net)','Cash Outflow',-75),
	(2020,'Operating Activities','Net Income','Cash Inflow',904),
	(2020,'Operating Activities','Income from discontinued operations (net tax)','Cash Inflow',0),
	(2020,'Operating Activities','Depreciation and amortization','Cash Inflow',146),
	(2020,'Operating Activities','Impairment and closure expense','Cash Inflow',172),
	(2020,'Operating Activities','Refranchising gain/loss','Cash Outflow',-34),
	(2020,'Operating Activities','Investment income/expense (net)','Cash Outflow',-74),
	(2020,'Operating Activities','Contributions to defined benefit pension plans','Cash Outflow',-6),
	(2020,'Operating Activities','Deferred income taxes','Cash Outflow',-65),
	(2020,'Operating Activities','Share-based compensation expense','Cash Inflow',97),
	(2020,'Operating Activities','Changes in accounts and notes receivable','Cash Inflow',62),
	(2020,'Operating Activities','Changes in prepaid expenses and other current assets','Cash Inflow',8),
	(2020,'Operating Activities','Changes in accounts payable and other current liabilities','Cash Inflow',128),
	(2020,'Operating Activities','Changes in income taxes payable','Cash Outflow',-110),
	(2020,'Operating Activities','Other (net)','Cash Inflow',77),
	(2020,'Investing Activities','Capital spending','Cash Outflow',-160),
	(2020,'Investing Activities','QuikOrder acquisition, net of cash acquired','Cash Inflow',0),
	(2020,'Investing Activities','Investment in Grubhub Inc. common stock','Cash Inflow',0),
	(2020,'Investing Activities','Acquisition of The Habit Restaurants, Inc. (net cash)','Cash Outflow',-408),
	(2020,'Investing Activities','Proceeds from sale/purchase of investment in Grubhub, Inc. (common stock)','Cash Inflow',206),
	(2020,'Investing Activities','Proceeds from sale of KFC Russia','Cash Inflow',0),
	(2020,'Investing Activities','Proceeds from refranchising of restaurants','Cash Inflow',19),
	(2020,'Investing Activities','Other (net)','Cash Inflow',8),
	(2020,'Financing Activities','Proceeds from long-term debt','Cash Inflow',1650),
	(2020,'Financing Activities','Repayments of long-term debt','Cash Outflow',-1517),
	(2020,'Financing Activities','Revolving credit facilities, three months or less, net','Cash Inflow',0),
	(2020,'Financing Activities','Short-term borrowings - More than three months – proceeds','Cash Inflow',95),
	(2020,'Financing Activities','Short-term borrowings - More than three months – payments','Cash Outflow',-100),
	(2020,'Financing Activities','Short-term borrowings -Three months or less, net','Cash Inflow',0),
	(2020,'Financing Activities','Repurchase shares of Common Stock','Cash Outflow',-239),
	(2020,'Financing Activities','Dividends paid on Common Stock','Cash Outflow',-566),
	(2020,'Financing Activities','Debt issuance costs','Cash Outflow',-20),
	(2020,'Financing Activities','Net transfers from discontinued operations','Cash Inflow',0),
	(2020,'Financing Activities','Other (net)','Cash Outflow',-41),
	(2021,'Operating Activities','Net Income','Cash Inflow',1575),
	(2021,'Operating Activities','Income from discontinued operations (net tax)','Cash Inflow',0),
	(2021,'Operating Activities','Depreciation and amortization','Cash Inflow',164),
	(2021,'Operating Activities','Impairment and closure expense','Cash Inflow',19),
	(2021,'Operating Activities','Refranchising gain/loss','Cash Outflow',-35),
	(2021,'Operating Activities','Investment income/expense (net)','Cash Outflow',-86),
	(2021,'Operating Activities','Contributions to defined benefit pension plans','Cash Inflow',0),
	(2021,'Operating Activities','Deferred income taxes','Cash Outflow',-200),
	(2021,'Operating Activities','Share-based compensation expense','Cash Inflow',75),
	(2021,'Operating Activities','Changes in accounts and notes receivable','Cash Outflow',-46),
	(2021,'Operating Activities','Changes in prepaid expenses and other current assets','Cash Outflow',-33),
	(2021,'Operating Activities','Changes in accounts payable and other current liabilities','Cash Inflow',122),
	(2021,'Operating Activities','Changes in income taxes payable','Cash Outflow',-41),
	(2021,'Operating Activities','Other (net)','Cash Inflow',192),
	(2021,'Investing Activities','Capital spending','Cash Outflow',-230),
	(2021,'Investing Activities','QuikOrder acquisition, net of cash acquired','Cash Inflow',0),
	(2021,'Investing Activities','Investment in Grubhub Inc. common stock','Cash Inflow',0),
	(2021,'Investing Activities','Acquisition of The Habit Restaurants, Inc. (net cash)','Cash Inflow',0),
	(2021,'Investing Activities','Proceeds from sale/purchase of investment in Grubhub, Inc. (common stock)','Cash Inflow',0),
	(2021,'Investing Activities','Proceeds from sale of KFC Russia','Cash Inflow',0),
	(2021,'Investing Activities','Proceeds from refranchising of restaurants','Cash Inflow',85),
	(2021,'Investing Activities','Other (net)','Cash Outflow',-28),
	(2021,'Financing Activities','Proceeds from long-term debt','Cash Inflow',4150),
	(2021,'Financing Activities','Repayments of long-term debt','Cash Outflow',-3657),
	(2021,'Financing Activities','Revolving credit facilities, three months or less, net','Cash Inflow',0),
	(2021,'Financing Activities','Short-term borrowings - More than three months – proceeds','Cash Inflow',0),
	(2021,'Financing Activities','Short-term borrowings - More than three months – payments','Cash Inflow',0),
	(2021,'Financing Activities','Short-term borrowings -Three months or less, net','Cash Inflow',0),
	(2021,'Financing Activities','Repurchase shares of Common Stock','Cash Outflow',-1591),
	(2021,'Financing Activities','Dividends paid on Common Stock','Cash Outflow',-592),
	(2021,'Financing Activities','Debt issuance costs','Cash Outflow',-37),
	(2021,'Financing Activities','Net transfers from discontinued operations','Cash Inflow',0),
	(2021,'Financing Activities','Other (net)','Cash Outflow',-40),
	(2022,'Operating Activities','Net Income','Cash Inflow',1325),
	(2022,'Operating Activities','Income from discontinued operations (net tax)','Cash Inflow',0),
	(2022,'Operating Activities','Depreciation and amortization','Cash Inflow',146),
	(2022,'Operating Activities','Impairment and closure expense','Cash Inflow',10),
	(2022,'Operating Activities','Refranchising gain/loss','Cash Outflow',-27),
	(2022,'Operating Activities','Investment income/expense (net)','Cash Outflow',-11),
	(2022,'Operating Activities','Contributions to defined benefit pension plans','Cash Inflow',0),
	(2022,'Operating Activities','Deferred income taxes','Cash Outflow',-55),
	(2022,'Operating Activities','Share-based compensation expense','Cash Inflow',84),
	(2022,'Operating Activities','Changes in accounts and notes receivable','Cash Outflow',-84),
	(2022,'Operating Activities','Changes in prepaid expenses and other current assets','Cash Inflow',1),
	(2022,'Operating Activities','Changes in accounts payable and other current liabilities','Cash Outflow',-39),
	(2022,'Operating Activities','Changes in income taxes payable','Cash Inflow',17),
	(2022,'Operating Activities','Other (net)','Cash Inflow',60),
	(2022,'Investing Activities','Capital spending','Cash Outflow',-279),
	(2022,'Investing Activities','QuikOrder acquisition, net of cash acquired','Cash Inflow',0),
	(2022,'Investing Activities','Investment in Grubhub Inc. common stock','Cash Inflow',0),
	(2022,'Investing Activities','Acquisition of The Habit Restaurants, Inc. (net cash)','Cash Inflow',0),
	(2022,'Investing Activities','Proceeds from sale/purchase of investment in Grubhub, Inc. (common stock)','Cash Inflow',0),
	(2022,'Investing Activities','Proceeds from sale of KFC Russia','Cash Inflow',0),
	(2022,'Investing Activities','Proceeds from refranchising of restaurants','Cash Inflow',73),
	(2022,'Investing Activities','Other (net)','Cash Inflow',4),
	(2022,'Financing Activities','Proceeds from long-term debt','Cash Inflow',999),
	(2022,'Financing Activities','Repayments of long-term debt','Cash Outflow',-699),
	(2022,'Financing Activities','Revolving credit facilities, three months or less, net','Cash Inflow',279),
	(2022,'Financing Activities','Short-term borrowings - More than three months – proceeds','Cash Inflow',0),
	(2022,'Financing Activities','Short-term borrowings - More than three months – payments','Cash Inflow',0),
	(2022,'Financing Activities','Short-term borrowings -Three months or less, net','Cash Inflow',0),
	(2022,'Financing Activities','Repurchase shares of Common Stock','Cash Outflow',-1200),
	(2022,'Financing Activities','Dividends paid on Common Stock','Cash Outflow',-649),
	(2022,'Financing Activities','Debt issuance costs','Cash Outflow',-11),
	(2022,'Financing Activities','Net transfers from discontinued operations','Cash Inflow',0),
	(2022,'Financing Activities','Other (net)','Cash Outflow',-42),
	(2023,'Operating Activities','Net Income','Cash Inflow',1134),
	(2023,'Operating Activities','Income from discontinued operations (net tax)','Cash Inflow',0),
	(2023,'Operating Activities','Depreciation and amortization','Cash Inflow',104),
	(2023,'Operating Activities','Impairment and closure expense','Cash Inflow',0),
	(2023,'Operating Activities','Refranchising gain/loss','Cash Outflow',-40),
	(2023,'Operating Activities','Investment income/expense (net)','Cash Outflow',-21),
	(2023,'Operating Activities','Contributions to defined benefit pension plans','Cash Inflow',0),
	(2023,'Operating Activities','Deferred income taxes','Cash Outflow',-93),
	(2023,'Operating Activities','Share-based compensation expense','Cash Inflow',69),
	(2023,'Operating Activities','Changes in accounts and notes receivable','Cash Outflow',-13),
	(2023,'Operating Activities','Changes in prepaid expenses and other current assets','Cash Outflow',-16),
	(2023,'Operating Activities','Changes in accounts payable and other current liabilities','Cash Outflow',-52),
	(2023,'Operating Activities','Changes in income taxes payable','Cash Outflow',-4),
	(2023,'Operating Activities','Other (net)','Cash Inflow',87),
	(2023,'Investing Activities','Capital spending','Cash Outflow',-179),
	(2023,'Investing Activities','QuikOrder acquisition, net of cash acquired','Cash Inflow',0),
	(2023,'Investing Activities','Investment in Grubhub Inc. common stock','Cash Inflow',0),
	(2023,'Investing Activities','Acquisition of The Habit Restaurants, Inc. (net cash)','Cash Inflow',0),
	(2023,'Investing Activities','Proceeds from sale/purchase of investment in Grubhub, Inc. (common stock)','Cash Inflow',0),
	(2023,'Investing Activities','Proceeds from sale of KFC Russia','Cash Inflow',121),
	(2023,'Investing Activities','Proceeds from refranchising of restaurants','Cash Inflow',57),
	(2023,'Investing Activities','Other (net)','Cash Outflow',-3),
	(2023,'Financing Activities','Proceeds from long-term debt','Cash Inflow',0),
	(2023,'Financing Activities','Repayments of long-term debt','Cash Outflow',-60),
	(2023,'Financing Activities','Revolving credit facilities, three months or less, net','Cash Outflow',-279),
	(2023,'Financing Activities','Short-term borrowings - More than three months – proceeds','Cash Inflow',0),
	(2023,'Financing Activities','Short-term borrowings - More than three months – payments','Cash Inflow',0),
	(2023,'Financing Activities','Short-term borrowings -Three months or less, net','Cash Inflow',0),
	(2023,'Financing Activities','Repurchase shares of Common Stock','Cash Outflow',-50),
	(2023,'Financing Activities','Dividends paid on Common Stock','Cash Outflow',-508),
	(2023,'Financing Activities','Debt issuance costs','Cash Inflow',0),
	(2023,'Financing Activities','Net transfers from discontinued operations','Cash Inflow',0),
	(2023,'Financing Activities','Other (net)','Cash Outflow',-24)
	(2018,'Foreign Exchange','Effect of Exchange Rate on Cash and Cash Equivalents','Cash Outflow',-63),
	(2019,'Foreign Exchange','Effect of Exchange Rate on Cash and Cash Equivalents','Cash Outflow',5),
	(2020,'Foreign Exchange','Effect of Exchange Rate on Cash and Cash Equivalents','Cash Outflow',24),
	(2021,'Foreign Exchange','Effect of Exchange Rate on Cash and Cash Equivalents','Cash Outflow',-19),
	(2022,'Foreign Exchange','Effect of Exchange Rate on Cash and Cash Equivalents','Cash Outflow',-26),
	(2023,'Foreign Exchange','Effect of Exchange Rate on Cash and Cash Equivalents','Cash Outflow',-2)
