

insert into 
	yum.Units_Franchise
values 
	('Bermuda',2018,'KFC',1,'Franchise and License'),
	('Bonaire',2018,'KFC',1,'Franchise and License'),
	('Dominica',2018,'KFC',1,'Franchise and License'),
	('Côte d''Ivoire',2018,'KFC',1,'Franchise and License'),
	('Latvia',2018,'KFC',1,'Franchise and License'),
	('Martinique',2018,'KFC',1,'Franchise and License'),
	('Military - Asia',2018,'KFC',1,'Franchise and License'),
	('Military - Iberia',2018,'KFC',1,'Franchise and License'),
	('Saipan',2018,'KFC',1,'Franchise and License'),
	('Slovenia',2018,'KFC',1,'Franchise and License'),
	('Saint Kitts and Nevis',2018,'KFC',1,'Franchise and License'),
	('Bermuda',2019,'KFC',1,'Franchise and License'),
	('Bonaire',2019,'KFC',1,'Franchise and License'),
	('Dominica',2019,'KFC',1,'Franchise and License'),
	('French Guiana',2019,'KFC',1,'Franchise and License'),
	('Gabon',2019,'KFC',1,'Franchise and License'),
	('Madagascar',2019,'KFC',1,'Franchise and License'),
	('Martinique',2019,'KFC',1,'Franchise and License'),
	('Military - Asia',2019,'KFC',1,'Franchise and License'),
	('Military - Iberia',2019,'KFC',1,'Franchise and License'),
	('Saipan',2019,'KFC',1,'Franchise and License'),
	('Slovenia',2019,'KFC',1,'Franchise and License'),
	('Saint Kitts and Nevis',2019,'KFC',1,'Franchise and License'),
	('Bermuda',2020,'KFC',1,'Franchise and License'),
	('Bonaire',2020,'KFC',1,'Franchise and License'),
	('Dominica',2020,'KFC',1,'Franchise and License'),
	('French Guiana',2020,'KFC',1,'Franchise and License'),
	('Martinique',2020,'KFC',1,'Franchise and License'),
	('Military - Asia',2020,'KFC',1,'Franchise and License'),
	('Military - Iberia',2020,'KFC',1,'Franchise and License'),
	('Rwanda',2020,'KFC',1,'Franchise and License'),
	('Saipan',2020,'KFC',1,'Franchise and License'),
	('Slovenia',2020,'KFC',1,'Franchise and License'),
	('Bermuda',2021,'KFC',1,'Franchise and License'),
	('Bonaire',2021,'KFC',1,'Franchise and License'),
	('Dominica',2021,'KFC',1,'Franchise and License'),
	('French Guiana',2021,'KFC',1,'Franchise and License'),
	('Martinique',2021,'KFC',1,'Franchise and License'),
	('Military - Iberia',2021,'KFC',1,'Franchise and License'),
	('Réunion',2021,'KFC',1,'Franchise and License'),
	('Rwanda',2021,'KFC',1,'Franchise and License'),
	('Saipan',2021,'KFC',1,'Franchise and License'),
	('Slovenia',2021,'KFC',1,'Franchise and License'),
	('Tajikistan',2021,'KFC',1,'Franchise and License'),
	('Bermuda',2022,'KFC',1,'Franchise and License'),
	('Bonaire',2022,'KFC',1,'Franchise and License'),
	('Dominica',2022,'KFC',1,'Franchise and License'),
	('French Guiana',2022,'KFC',1,'Franchise and License'),
	('Martinique',2022,'KFC',1,'Franchise and License'),
	('Military - Iberia',2022,'KFC',1,'Franchise and License'),
	('Rwanda',2022,'KFC',1,'Franchise and License'),
	('Saipan',2022,'KFC',1,'Franchise and License'),
	('Slovenia',2022,'KFC',1,'Franchise and License'),
	('Bermuda',2023,'KFC',1,'Franchise and License'),
	('Bonaire',2023,'KFC',1,'Franchise and License'),
	('Dominica',2023,'KFC',1,'Franchise and License'),
	('French Guiana',2023,'KFC',1,'Franchise and License'),
	('Martinique',2023,'KFC',1,'Franchise and License'),
	('Rwanda',2023,'KFC',1,'Franchise and License'),
	('Saipan',2023,'KFC',1,'Franchise and License'),
	('Slovenia',2023,'KFC',1,'Franchise and License'),
	('Andorra',2018,'Pizza Hut',1,'Franchise and License'),
	('Angola',2018,'Pizza Hut',1,'Franchise and License'),
	('Gibraltar',2018,'Pizza Hut',1,'Franchise and License'),
	('Kazakhstan',2018,'Pizza Hut',1,'Franchise and License'),
	('Lithuania',2018,'Pizza Hut',1,'Franchise and License'),
	('Military - Africa',2018,'Pizza Hut',1,'Franchise and License'),
	('Military - Latin America',2018,'Pizza Hut',1,'Franchise and License'),
	('Saipan',2018,'Pizza Hut',1,'Franchise and License'),
	('US Virgin Islands',2018,'Pizza Hut',1,'Franchise and License'),
	('Andorra',2019,'Pizza Hut',1,'Franchise and License'),
	('Angola',2019,'Pizza Hut',1,'Franchise and License'),
	('Gibraltar',2019,'Pizza Hut',1,'Franchise and License'),
	('Military - Africa',2019,'Pizza Hut',1,'Franchise and License'),
	('Military - Latin America',2019,'Pizza Hut',1,'Franchise and License'),
	('Saipan',2019,'Pizza Hut',1,'Franchise and License'),
	('Andorra',2020,'Pizza Hut',1,'Franchise and License'),
	('Angola',2020,'Pizza Hut',1,'Franchise and License'),
	('Djibouti',2020,'Pizza Hut',1,'Franchise and License'),
	('Gibraltar',2020,'Pizza Hut',1,'Franchise and License'),
	('Military - Africa',2020,'Pizza Hut',1,'Franchise and License'),
	('Saipan',2020,'Pizza Hut',1,'Franchise and License'),
	('Uganda',2020,'Pizza Hut',1,'Franchise and License'),
	('Andorra',2021,'Pizza Hut',1,'Franchise and License'),
	('Angola',2021,'Pizza Hut',1,'Franchise and License'),
	('Djibouti',2021,'Pizza Hut',1,'Franchise and License'),
	('Gibraltar',2021,'Pizza Hut',1,'Franchise and License'),
	('Military - Africa',2021,'Pizza Hut',1,'Franchise and License'),
	('Saipan',2021,'Pizza Hut',1,'Franchise and License'),
	('Uganda',2021,'Pizza Hut',1,'Franchise and License'),
	('Albania',2022,'Pizza Hut',1,'Franchise and License'),
	('Andorra',2022,'Pizza Hut',1,'Franchise and License'),
	('Angola',2022,'Pizza Hut',1,'Franchise and License'),
	('Djibouti',2022,'Pizza Hut',1,'Franchise and License'),
	('Gibraltar',2022,'Pizza Hut',1,'Franchise and License'),
	('Grenada',2022,'Pizza Hut',1,'Franchise and License'),
	('Iceland',2022,'Pizza Hut',1,'Franchise and License'),
	('Military - Africa',2022,'Pizza Hut',1,'Franchise and License'),
	('Saipan',2022,'Pizza Hut',1,'Franchise and License'),
	('Uganda',2022,'Pizza Hut',1,'Franchise and License'),
	('Andorra',2023,'Pizza Hut',1,'Franchise and License'),
	('Angola',2023,'Pizza Hut',1,'Franchise and License'),
	('Djibouti',2023,'Pizza Hut',1,'Franchise and License'),
	('Gibraltar',2023,'Pizza Hut',1,'Franchise and License'),
	('Grenada',2023,'Pizza Hut',1,'Franchise and License'),
	('Iceland',2023,'Pizza Hut',1,'Franchise and License'),
	('Iraq',2023,'Pizza Hut',1,'Franchise and License'),
	('Military - Africa',2023,'Pizza Hut',1,'Franchise and License'),
	('Saipan',2023,'Pizza Hut',1,'Franchise and License'),
	('Somaliland',2023,'Pizza Hut',1,'Franchise and License'),
	('Uganda',2023,'Pizza Hut',1,'Franchise and License'),
	('Military - Latin America',2018,'Taco Bell',1,'Franchise and License'),
	('Military - Latin America',2019,'Taco Bell',1,'Franchise and License'),
	('New Zealand',2019,'Taco Bell',1,'Franchise and License'),
	('Indonesia',2020,'Taco Bell',1,'Franchise and License'),
	('Military - Latin America',2020,'Taco Bell',1,'Franchise and License'),
	('Military - Latin America',2021,'Taco Bell',1,'Franchise and License'),
	('Military - Latin America',2022,'Taco Bell',1,'Franchise and License'),
	('Military - Latin America',2023,'Taco Bell',1,'Franchise and License'),
	('Albania',2018,'KFC',2,'Franchise and License'),
	('Antigua and Barbuda',2018,'KFC',2,'Franchise and License'),
	('Malawi',2018,'KFC',2,'Franchise and License'),
	('Maldives',2018,'KFC',2,'Franchise and License'),
	('Moldova',2018,'KFC',2,'Franchise and License'),
	('Saint Vincent and the Grenadines',2018,'KFC',2,'Franchise and License'),
	('Albania',2019,'KFC',2,'Franchise and License'),
	('Estonia',2019,'KFC',2,'Franchise and License'),
	('Latvia',2019,'KFC',2,'Franchise and License'),
	('Malawi',2019,'KFC',2,'Franchise and License'),
	('Maldives',2019,'KFC',2,'Franchise and License'),
	('Moldova',2019,'KFC',2,'Franchise and License'),
	('Senegal',2019,'KFC',2,'Franchise and License'),
	('Saint Vincent and the Grenadines',2019,'KFC',2,'Franchise and License'),
	('Madagascar',2020,'KFC',2,'Franchise and License'),
	('Malawi',2020,'KFC',2,'Franchise and License'),
	('Maldives',2020,'KFC',2,'Franchise and License'),
	('Moldova',2020,'KFC',2,'Franchise and License'),
	('Saint Kitts and Nevis',2020,'KFC',2,'Franchise and License'),
	('Saint Vincent and the Grenadines',2020,'KFC',2,'Franchise and License'),
	('Madagascar',2021,'KFC',2,'Franchise and License'),
	('Malawi',2021,'KFC',2,'Franchise and License'),
	('Maldives',2021,'KFC',2,'Franchise and License'),
	('Moldova',2021,'KFC',2,'Franchise and License'),
	('Saint Kitts and Nevis',2021,'KFC',2,'Franchise and License'),
	('Saint Vincent and the Grenadines',2021,'KFC',2,'Franchise and License'),
	('Bosnia and Herzegovina',2022,'KFC',2,'Franchise and License'),
	('Madagascar',2022,'KFC',2,'Franchise and License'),
	('Maldives',2022,'KFC',2,'Franchise and License'),
	('Moldova',2022,'KFC',2,'Franchise and License'),
	('Réunion',2022,'KFC',2,'Franchise and License'),
	('Saint Kitts and Nevis',2022,'KFC',2,'Franchise and License'),
	('Saint Maarten',2022,'KFC',2,'Franchise and License'),
	('Saint Vincent and the Grenadines',2022,'KFC',2,'Franchise and License'),
	('Madagascar',2023,'KFC',2,'Franchise and License'),
	('Moldova',2023,'KFC',2,'Franchise and License'),
	('Saint Kitts and Nevis',2023,'KFC',2,'Franchise and License'),
	('Saint Maarten',2023,'KFC',2,'Franchise and License'),
	('Saint Vincent and the Grenadines',2023,'KFC',2,'Franchise and License'),
	('Algeria',2018,'Pizza Hut',2,'Franchise and License'),
	('Armenia',2018,'Pizza Hut',2,'Franchise and License'),
	('Azerbaijan',2018,'Pizza Hut',2,'Franchise and License'),
	('Grand Cayman',2018,'Pizza Hut',2,'Franchise and License'),
	('Grenada',2018,'Pizza Hut',2,'Franchise and License'),
	('Guadeloupe',2018,'Pizza Hut',2,'Franchise and License'),
	('Iceland',2018,'Pizza Hut',2,'Franchise and License'),
	('Maldives',2018,'Pizza Hut',2,'Franchise and License'),
	('Slovakia',2018,'Pizza Hut',2,'Franchise and License'),
	('Suriname',2018,'Pizza Hut',2,'Franchise and License'),
	('Zimbabwe',2018,'Pizza Hut',2,'Franchise and License'),
	('Azerbaijan',2019,'Pizza Hut',2,'Franchise and License'),
	('Grand Cayman',2019,'Pizza Hut',2,'Franchise and License'),
	('Grenada',2019,'Pizza Hut',2,'Franchise and License'),
	('Guadeloupe',2019,'Pizza Hut',2,'Franchise and License'),
	('Iceland',2019,'Pizza Hut',2,'Franchise and License'),
	('Côte d''Ivoire',2019,'Pizza Hut',2,'Franchise and License'),
	('Maldives',2019,'Pizza Hut',2,'Franchise and License'),
	('Suriname',2019,'Pizza Hut',2,'Franchise and License'),
	('US Virgin Islands',2019,'Pizza Hut',2,'Franchise and License'),
	('Algeria',2020,'Pizza Hut',2,'Franchise and License'),
	('Aruba',2020,'Pizza Hut',2,'Franchise and License'),
	('Azerbaijan',2020,'Pizza Hut',2,'Franchise and License'),
	('Cameroon',2020,'Pizza Hut',2,'Franchise and License'),
	('Grand Cayman',2020,'Pizza Hut',2,'Franchise and License'),
	('Grenada',2020,'Pizza Hut',2,'Franchise and License'),
	('Guadeloupe',2020,'Pizza Hut',2,'Franchise and License'),
	('Iceland',2020,'Pizza Hut',2,'Franchise and License'),
	('Côte d''Ivoire',2020,'Pizza Hut',2,'Franchise and License'),
	('Maldives',2020,'Pizza Hut',2,'Franchise and License'),
	('Suriname',2020,'Pizza Hut',2,'Franchise and License'),
	('US Virgin Islands',2020,'Pizza Hut',2,'Franchise and License'),
	('Cameroon',2021,'Pizza Hut',2,'Franchise and License'),
	('Gabon',2021,'Pizza Hut',2,'Franchise and License'),
	('Grand Cayman',2021,'Pizza Hut',2,'Franchise and License'),
	('Grenada',2021,'Pizza Hut',2,'Franchise and License'),
	('Guadeloupe',2021,'Pizza Hut',2,'Franchise and License'),
	('Iceland',2021,'Pizza Hut',2,'Franchise and License'),
	('Maldives',2021,'Pizza Hut',2,'Franchise and License'),
	('Suriname',2021,'Pizza Hut',2,'Franchise and License'),
	('US Virgin Islands',2021,'Pizza Hut',2,'Franchise and License'),
	('Grand Cayman',2022,'Pizza Hut',2,'Franchise and License'),
	('Côte d''Ivoire',2022,'Pizza Hut',2,'Franchise and License'),
	('Maldives',2022,'Pizza Hut',2,'Franchise and License'),
	('Suriname',2022,'Pizza Hut',2,'Franchise and License'),
	('US Virgin Islands',2022,'Pizza Hut',2,'Franchise and License'),
	('Albania',2023,'Pizza Hut',2,'Franchise and License'),
	('Grand Cayman',2023,'Pizza Hut',2,'Franchise and License'),
	('Côte d''Ivoire',2023,'Pizza Hut',2,'Franchise and License'),
	('Suriname',2023,'Pizza Hut',2,'Franchise and License'),
	('US Virgin Islands',2023,'Pizza Hut',2,'Franchise and License'),
	('Peru',2018,'Taco Bell',2,'Franchise and License'),
	('Portugal',2019,'Taco Bell',2,'Franchise and License'),
	('Cambodia',2020,'Habit',2,'Franchise and License'),
	('Bolivia',2018,'KFC',3,'Franchise and License'),
	('Grand Cayman',2018,'KFC',3,'Franchise and License'),
	('Lithuania',2018,'KFC',3,'Franchise and License'),
	('North Macedonia',2018,'KFC',3,'Franchise and License'),
	('Malta',2018,'KFC',3,'Franchise and License'),
	('Paraguay',2018,'KFC',3,'Franchise and License'),
	('Saint Maarten',2018,'KFC',3,'Franchise and License'),
	('Tunisia',2018,'KFC',3,'Franchise and License'),
	('Uzbekistan',2018,'KFC',3,'Franchise and License'),
	('Antigua and Barbuda',2019,'KFC',3,'Franchise and License'),
	('Belgium',2019,'KFC',3,'Franchise and License'),
	('Bolivia',2019,'KFC',3,'Franchise and License'),
	('Grand Cayman',2019,'KFC',3,'Franchise and License'),
	('Lithuania',2019,'KFC',3,'Franchise and License'),
	('Malta',2019,'KFC',3,'Franchise and License'),
	('Saint Maarten',2019,'KFC',3,'Franchise and License'),
	('Sudan',2019,'KFC',3,'Franchise and License'),
	('Antigua and Barbuda',2020,'KFC',3,'Franchise and License'),
	('Bolivia',2020,'KFC',3,'Franchise and License'),
	('Grand Cayman',2020,'KFC',3,'Franchise and License'),
	('Lithuania',2020,'KFC',3,'Franchise and License'),
	('Malta',2020,'KFC',3,'Franchise and License'),
	('Senegal',2020,'KFC',3,'Franchise and License'),
	('Saint Maarten',2020,'KFC',3,'Franchise and License'),
	('Antigua and Barbuda',2021,'KFC',3,'Franchise and License'),
	('Bolivia',2021,'KFC',3,'Franchise and License'),
	('Grand Cayman',2021,'KFC',3,'Franchise and License'),
	('Malta',2021,'KFC',3,'Franchise and License'),
	('Saint Maarten',2021,'KFC',3,'Franchise and License'),
	('Antigua and Barbuda',2022,'KFC',3,'Franchise and License'),
	('Bolivia',2022,'KFC',3,'Franchise and License'),
	('Grand Cayman',2022,'KFC',3,'Franchise and License'),
	('Guadeloupe',2022,'KFC',3,'Franchise and License'),
	('Malawi',2022,'KFC',3,'Franchise and License'),
	('Malta',2022,'KFC',3,'Franchise and License'),
	('Tajikistan',2022,'KFC',3,'Franchise and License'),
	('Antigua and Barbuda',2023,'KFC',3,'Franchise and License'),
	('Bolivia',2023,'KFC',3,'Franchise and License'),
	('Bosnia and Herzegovina',2023,'KFC',3,'Franchise and License'),
	('Grand Cayman',2023,'KFC',3,'Franchise and License'),
	('Guadeloupe',2023,'KFC',3,'Franchise and License'),
	('Macau',2023,'KFC',3,'Franchise and License'),
	('Malawi',2023,'KFC',3,'Franchise and License'),
	('Maldives',2023,'KFC',3,'Franchise and License'),
	('Malta',2023,'KFC',3,'Franchise and License'),
	('Réunion',2023,'KFC',3,'Franchise and License'),
	('Aruba',2018,'Pizza Hut',3,'Franchise and License'),
	('Botswana',2018,'Pizza Hut',3,'Franchise and License'),
	('Ethiopia',2018,'Pizza Hut',3,'Franchise and License'),
	('Mozambique',2018,'Pizza Hut',3,'Franchise and License'),
	('Nepal',2018,'Pizza Hut',3,'Franchise and License'),
	('Netherlands',2018,'Pizza Hut',3,'Franchise and License'),
	('Nigeria',2018,'Pizza Hut',3,'Franchise and License'),
	('Algeria',2019,'Pizza Hut',3,'Franchise and License'),
	('Armenia',2019,'Pizza Hut',3,'Franchise and License'),
	('Aruba',2019,'Pizza Hut',3,'Franchise and License'),
	('Botswana',2019,'Pizza Hut',3,'Franchise and License'),
	('Kazakhstan',2019,'Pizza Hut',3,'Franchise and License'),
	('Nepal',2019,'Pizza Hut',3,'Franchise and License'),
	('Nigeria',2019,'Pizza Hut',3,'Franchise and License'),
	('Slovakia',2019,'Pizza Hut',3,'Franchise and License'),
	('Zimbabwe',2019,'Pizza Hut',3,'Franchise and License'),
	('Botswana',2020,'Pizza Hut',3,'Franchise and License'),
	('Kazakhstan',2020,'Pizza Hut',3,'Franchise and License'),
	('Nepal',2020,'Pizza Hut',3,'Franchise and License'),
	('Nigeria',2020,'Pizza Hut',3,'Franchise and License'),
	('Slovakia',2020,'Pizza Hut',3,'Franchise and License'),
	('Zimbabwe',2020,'Pizza Hut',3,'Franchise and License'),
	('Aruba',2021,'Pizza Hut',3,'Franchise and License'),
	('Botswana',2021,'Pizza Hut',3,'Franchise and License'),
	('Côte d''Ivoire',2021,'Pizza Hut',3,'Franchise and License'),
	('Kazakhstan',2021,'Pizza Hut',3,'Franchise and License'),
	('Nepal',2021,'Pizza Hut',3,'Franchise and License'),
	('Slovakia',2021,'Pizza Hut',3,'Franchise and License'),
	('Zimbabwe',2021,'Pizza Hut',3,'Franchise and License'),
	('Aruba',2022,'Pizza Hut',3,'Franchise and License'),
	('Gabon',2022,'Pizza Hut',3,'Franchise and License'),
	('Kazakhstan',2022,'Pizza Hut',3,'Franchise and License'),
	('Slovakia',2022,'Pizza Hut',3,'Franchise and License'),
	('Aruba',2023,'Pizza Hut',3,'Franchise and License'),
	('Gabon',2023,'Pizza Hut',3,'Franchise and License'),
	('Kazakhstan',2023,'Pizza Hut',3,'Franchise and License'),
	('Maldives',2023,'Pizza Hut',3,'Franchise and License'),
	('Slovakia',2023,'Pizza Hut',3,'Franchise and License'),
	('Aruba',2018,'Taco Bell',3,'Franchise and License'),
	('Netherlands',2018,'Taco Bell',3,'Franchise and License'),
	('Sri Lanka',2018,'Taco Bell',3,'Franchise and License'),
	('Aruba',2019,'Taco Bell',3,'Franchise and License'),
	('Netherlands',2019,'Taco Bell',3,'Franchise and License'),
	('Sri Lanka',2019,'Taco Bell',3,'Franchise and License'),
	('Aruba',2020,'Taco Bell',3,'Franchise and License'),
	('Sri Lanka',2020,'Taco Bell',3,'Franchise and License'),
	('Aruba',2021,'Taco Bell',3,'Franchise and License'),
	('Indonesia',2021,'Taco Bell',3,'Franchise and License'),
	('Military - MENA',2021,'Taco Bell',3,'Franchise and License'),
	('Aruba',2022,'Taco Bell',3,'Franchise and License'),
	('Aruba',2023,'Taco Bell',3,'Franchise and License'),
	('Aruba',2018,'KFC',4,'Franchise and License'),
	('Grenada',2018,'KFC',4,'Franchise and License'),
	('Kyrgyzstan',2018,'KFC',4,'Franchise and License'),
	('Slovakia',2018,'KFC',4,'Franchise and License'),
	('Saint Lucia',2018,'KFC',4,'Franchise and License'),
	('Switzerland',2018,'KFC',4,'Franchise and License'),
	('Zambia',2018,'KFC',4,'Franchise and License'),
	('Grenada',2019,'KFC',4,'Franchise and License'),
	('Côte d''Ivoire',2019,'KFC',4,'Franchise and License'),
	('Paraguay',2019,'KFC',4,'Franchise and License'),
	('Slovakia',2019,'KFC',4,'Franchise and License'),
	('Saint Lucia',2019,'KFC',4,'Franchise and License'),
	('Zambia',2019,'KFC',4,'Franchise and License'),
	('Gabon',2020,'KFC',4,'Franchise and License'),
	('Grenada',2020,'KFC',4,'Franchise and License'),
	('Israel',2020,'KFC',4,'Franchise and License'),
	('Latvia',2020,'KFC',4,'Franchise and License'),
	('Macau',2020,'KFC',4,'Franchise and License'),
	('North Macedonia',2020,'KFC',4,'Franchise and License'),
	('Paraguay',2020,'KFC',4,'Franchise and License'),
	('Saint Lucia',2020,'KFC',4,'Franchise and License'),
	('Sudan',2020,'KFC',4,'Franchise and License'),
	('Zambia',2020,'KFC',4,'Franchise and License'),
	('Finland',2021,'KFC',4,'Franchise and License'),
	('Gabon',2021,'KFC',4,'Franchise and License'),
	('Grenada',2021,'KFC',4,'Franchise and License'),
	('Macau',2021,'KFC',4,'Franchise and License'),
	('Gabon',2022,'KFC',4,'Franchise and License'),
	('Grenada',2022,'KFC',4,'Franchise and License'),
	('Macau',2022,'KFC',4,'Franchise and License'),
	('Gabon',2023,'KFC',4,'Franchise and License'),
	('Grenada',2023,'KFC',4,'Franchise and License'),
	('Tajikistan',2023,'KFC',4,'Franchise and License'),
	('Bahamas',2018,'Pizza Hut',4,'Franchise and License'),
	('Curacao',2018,'Pizza Hut',4,'Franchise and License'),
	('Bahamas',2019,'Pizza Hut',4,'Franchise and License'),
	('Curacao',2019,'Pizza Hut',4,'Franchise and License'),
	('Mozambique',2019,'Pizza Hut',4,'Franchise and License'),
	('Netherlands',2019,'Pizza Hut',4,'Franchise and License'),
	('Sudan',2019,'Pizza Hut',4,'Franchise and License'),
	('Armenia',2020,'Pizza Hut',4,'Franchise and License'),
	('Bahamas',2020,'Pizza Hut',4,'Franchise and License'),
	('Curacao',2020,'Pizza Hut',4,'Franchise and License'),
	('Kenya',2020,'Pizza Hut',4,'Franchise and License'),
	('Mozambique',2020,'Pizza Hut',4,'Franchise and License'),
	('Sudan',2020,'Pizza Hut',4,'Franchise and License'),
	('Algeria',2021,'Pizza Hut',4,'Franchise and License'),
	('Bahamas',2021,'Pizza Hut',4,'Franchise and License'),
	('Cambodia',2021,'Pizza Hut',4,'Franchise and License'),
	('Curacao',2021,'Pizza Hut',4,'Franchise and License'),
	('Kenya',2021,'Pizza Hut',4,'Franchise and License'),
	('Sudan',2021,'Pizza Hut',4,'Franchise and License'),
	('Bahamas',2022,'Pizza Hut',4,'Franchise and License'),
	('Bolivia',2022,'Pizza Hut',4,'Franchise and License'),
	('Curacao',2022,'Pizza Hut',4,'Franchise and License'),
	('Mauritius',2022,'Pizza Hut',4,'Franchise and License'),
	('Nepal',2022,'Pizza Hut',4,'Franchise and License'),
	('Bahamas',2023,'Pizza Hut',4,'Franchise and License'),
	('Curacao',2023,'Pizza Hut',4,'Franchise and License'),
	('Mauritius',2023,'Pizza Hut',4,'Franchise and License'),
	('Nepal',2023,'Pizza Hut',4,'Franchise and License'),
	('Sudan',2023,'Pizza Hut',4,'Franchise and License'),
	('Australia',2018,'Taco Bell',4,'Franchise and License'),
	('China',2018,'Taco Bell',4,'Franchise and License'),
	('Peru',2019,'Taco Bell',4,'Franchise and License'),
	('Military - MENA',2020,'Taco Bell',4,'Franchise and License'),
	('Netherlands',2020,'Taco Bell',4,'Franchise and License'),
	('New Zealand',2020,'Taco Bell',4,'Franchise and License'),
	('Peru',2020,'Taco Bell',4,'Franchise and License'),
	('Portugal',2020,'Taco Bell',4,'Franchise and License'),
	('Malaysia',2021,'Taco Bell',4,'Franchise and License'),
	('Military - MENA',2022,'Taco Bell',4,'Franchise and License'),
	('Military - MENA',2023,'Taco Bell',4,'Franchise and License'),
	('Cambodia',2021,'Habit',4,'Franchise and License'),
	('Georgia',2018,'KFC',5,'Franchise and License'),
	('Guadeloupe',2018,'KFC',5,'Franchise and License'),
	('Guyana',2018,'KFC',5,'Franchise and License'),
	('Tanzania',2018,'KFC',5,'Franchise and License'),
	('US Virgin Islands',2018,'KFC',5,'Franchise and License'),
	('Aruba',2019,'KFC',5,'Franchise and License'),
	('Georgia',2019,'KFC',5,'Franchise and License'),
	('Guadeloupe',2019,'KFC',5,'Franchise and License'),
	('Macau',2019,'KFC',5,'Franchise and License'),
	('North Macedonia',2019,'KFC',5,'Franchise and License'),
	('US Virgin Islands',2019,'KFC',5,'Franchise and License'),
	('Albania',2020,'KFC',5,'Franchise and License'),
	('Aruba',2020,'KFC',5,'Franchise and License'),
	('Estonia',2020,'KFC',5,'Franchise and License'),
	('Guadeloupe',2020,'KFC',5,'Franchise and License'),
	('Slovakia',2020,'KFC',5,'Franchise and License'),
	('Aruba',2021,'KFC',5,'Franchise and License'),
	('Guadeloupe',2021,'KFC',5,'Franchise and License'),
	('Latvia',2021,'KFC',5,'Franchise and License'),
	('North Macedonia',2021,'KFC',5,'Franchise and License'),
	('Paraguay',2021,'KFC',5,'Franchise and License'),
	('Senegal',2021,'KFC',5,'Franchise and License'),
	('Saint Lucia',2021,'KFC',5,'Franchise and License'),
	('Zambia',2021,'KFC',5,'Franchise and License'),
	('Aruba',2022,'KFC',5,'Franchise and License'),
	('Latvia',2022,'KFC',5,'Franchise and License'),
	('North Macedonia',2022,'KFC',5,'Franchise and License'),
	('Senegal',2022,'KFC',5,'Franchise and License'),
	('Saint Lucia',2022,'KFC',5,'Franchise and License'),
	('Aruba',2023,'KFC',5,'Franchise and License'),
	('Finland',2023,'KFC',5,'Franchise and License'),
	('North Macedonia',2023,'KFC',5,'Franchise and License'),
	('Saint Lucia',2023,'KFC',5,'Franchise and License'),
	('Malta',2018,'Pizza Hut',5,'Franchise and License'),
	('Tanzania',2018,'Pizza Hut',5,'Franchise and License'),
	('Tunisia',2018,'Pizza Hut',5,'Franchise and License'),
	('Uganda',2018,'Pizza Hut',5,'Franchise and License'),
	('West Bank',2018,'Pizza Hut',5,'Franchise and License'),
	('Ethiopia',2019,'Pizza Hut',5,'Franchise and License'),
	('Guam',2019,'Pizza Hut',5,'Franchise and License'),
	('Kenya',2019,'Pizza Hut',5,'Franchise and License'),
	('Malta',2019,'Pizza Hut',5,'Franchise and License'),
	('Tunisia',2019,'Pizza Hut',5,'Franchise and License'),
	('Uganda',2019,'Pizza Hut',5,'Franchise and License'),
	('Ethiopia',2020,'Pizza Hut',5,'Franchise and License'),
	('Guam',2020,'Pizza Hut',5,'Franchise and License'),
	('Malta',2020,'Pizza Hut',5,'Franchise and License'),
	('Tunisia',2020,'Pizza Hut',5,'Franchise and License'),
	('Azerbaijan',2021,'Pizza Hut',5,'Franchise and License'),
	('Ethiopia',2021,'Pizza Hut',5,'Franchise and License'),
	('Guam',2021,'Pizza Hut',5,'Franchise and License'),
	('Malta',2021,'Pizza Hut',5,'Franchise and License'),
	('Mauritius',2021,'Pizza Hut',5,'Franchise and License'),
	('Military - MENA',2021,'Pizza Hut',5,'Franchise and License'),
	('Tunisia',2021,'Pizza Hut',5,'Franchise and License'),
	('Algeria',2022,'Pizza Hut',5,'Franchise and License'),
	('Azerbaijan',2022,'Pizza Hut',5,'Franchise and License'),
	('Guam',2022,'Pizza Hut',5,'Franchise and License'),
	('Kenya',2022,'Pizza Hut',5,'Franchise and License'),
	('Lebanon',2022,'Pizza Hut',5,'Franchise and License'),
	('Military - MENA',2022,'Pizza Hut',5,'Franchise and License'),
	('Sudan',2022,'Pizza Hut',5,'Franchise and License'),
	('Zimbabwe',2022,'Pizza Hut',5,'Franchise and License'),
	('Algeria',2023,'Pizza Hut',5,'Franchise and License'),
	('Guam',2023,'Pizza Hut',5,'Franchise and License'),
	('Malta',2023,'Pizza Hut',5,'Franchise and License'),
	('Military - MENA',2023,'Pizza Hut',5,'Franchise and License'),
	('Zimbabwe',2023,'Pizza Hut',5,'Franchise and License'),
	('Cyprus',2018,'Taco Bell',5,'Franchise and License'),
	('Finland',2018,'Taco Bell',5,'Franchise and License'),
	('Military - MENA',2018,'Taco Bell',5,'Franchise and License'),
	('Romania',2018,'Taco Bell',5,'Franchise and License'),
	('Cyprus',2019,'Taco Bell',5,'Franchise and License'),
	('Military - MENA',2019,'Taco Bell',5,'Franchise and License'),
	('Thailand',2019,'Taco Bell',5,'Franchise and License'),
	('Cyprus',2020,'Taco Bell',5,'Franchise and License'),
	('Sri Lanka',2021,'Taco Bell',5,'Franchise and License'),
	('China',2022,'Habit',5,'Franchise and License'),
	('China',2023,'Habit',5,'Franchise and License'),
	('Suriname',2018,'KFC',6,'Franchise and License'),
	('Zimbabwe',2018,'KFC',6,'Franchise and License'),
	('Kyrgyzstan',2019,'KFC',6,'Franchise and License'),
	('Suriname',2019,'KFC',6,'Franchise and License'),
	('Tanzania',2019,'KFC',6,'Franchise and License'),
	('Zimbabwe',2019,'KFC',6,'Franchise and License'),
	('Côte d''Ivoire',2020,'KFC',6,'Franchise and License'),
	('Suriname',2020,'KFC',6,'Franchise and License'),
	('Tanzania',2020,'KFC',6,'Franchise and License'),
	('US Virgin Islands',2020,'KFC',6,'Franchise and License'),
	('Zimbabwe',2020,'KFC',6,'Franchise and License'),
	('Curacao',2021,'KFC',6,'Franchise and License'),
	('Côte d''Ivoire',2021,'KFC',6,'Franchise and License'),
	('Lithuania',2021,'KFC',6,'Franchise and License'),
	('Slovakia',2021,'KFC',6,'Franchise and License'),
	('Sudan',2021,'KFC',6,'Franchise and License'),
	('Suriname',2021,'KFC',6,'Franchise and License'),
	('Tanzania',2021,'KFC',6,'Franchise and License'),
	('US Virgin Islands',2021,'KFC',6,'Franchise and License'),
	('Zimbabwe',2021,'KFC',6,'Franchise and License'),
	('Curacao',2022,'KFC',6,'Franchise and License'),
	('Finland',2022,'KFC',6,'Franchise and License'),
	('Côte d''Ivoire',2022,'KFC',6,'Franchise and License'),
	('Paraguay',2022,'KFC',6,'Franchise and License'),
	('US Virgin Islands',2022,'KFC',6,'Franchise and License'),
	('Curacao',2023,'KFC',6,'Franchise and License'),
	('Côte d''Ivoire',2023,'KFC',6,'Franchise and License'),
	('Latvia',2023,'KFC',6,'Franchise and License'),
	('Paraguay',2023,'KFC',6,'Franchise and License'),
	('Senegal',2023,'KFC',6,'Franchise and License'),
	('US Virgin Islands',2023,'KFC',6,'Franchise and License'),
	('Guam',2018,'Pizza Hut',6,'Franchise and License'),
	('Guyana',2018,'Pizza Hut',6,'Franchise and License'),
	('Kenya',2018,'Pizza Hut',6,'Franchise and License'),
	('Zambia',2018,'Pizza Hut',6,'Franchise and License'),
	('Zambia',2019,'Pizza Hut',6,'Franchise and License'),
	('Military - MENA',2020,'Pizza Hut',6,'Franchise and License'),
	('Bolivia',2021,'Pizza Hut',6,'Franchise and License'),
	('Ethiopia',2022,'Pizza Hut',6,'Franchise and License'),
	('Malta',2022,'Pizza Hut',6,'Franchise and License'),
	('Ethiopia',2023,'Pizza Hut',6,'Franchise and License'),
	('Kenya',2023,'Pizza Hut',6,'Franchise and License'),
	('El Salvador',2018,'Taco Bell',6,'Franchise and License'),
	('El Salvador',2020,'Taco Bell',6,'Franchise and License'),
	('Cyprus',2021,'Taco Bell',6,'Franchise and License'),
	('Netherlands',2021,'Taco Bell',6,'Franchise and License'),
	('Peru',2021,'Taco Bell',6,'Franchise and License'),
	('Cyprus',2022,'Taco Bell',6,'Franchise and License'),
	('Indonesia',2022,'Taco Bell',6,'Franchise and License'),
	('Netherlands',2022,'Taco Bell',6,'Franchise and License'),
	('Peru',2022,'Taco Bell',6,'Franchise and License'),
	('Cyprus',2023,'Taco Bell',6,'Franchise and License'),
	('Peru',2023,'Taco Bell',6,'Franchise and License'),
	('Cambodia',2022,'Habit',6,'Franchise and License'),
	('Austria',2018,'KFC',7,'Franchise and License'),
	('Curacao',2018,'KFC',7,'Franchise and License'),
	('El Salvador',2018,'KFC',7,'Franchise and License'),
	('Guatemala',2018,'KFC',7,'Franchise and License'),
	('Lesotho',2018,'KFC',7,'Franchise and License'),
	('Nepal',2018,'KFC',7,'Franchise and License'),
	('Swaziland',2018,'KFC',7,'Franchise and License'),
	('Curacao',2019,'KFC',7,'Franchise and License'),
	('Guatemala',2019,'KFC',7,'Franchise and License'),
	('Guyana',2019,'KFC',7,'Franchise and License'),
	('Nepal',2019,'KFC',7,'Franchise and License'),
	('Switzerland',2019,'KFC',7,'Franchise and License'),
	('Tunisia',2019,'KFC',7,'Franchise and License'),
	('Uzbekistan',2019,'KFC',7,'Franchise and License'),
	('Belgium',2020,'KFC',7,'Franchise and License'),
	('Curacao',2020,'KFC',7,'Franchise and License'),
	('Guatemala',2020,'KFC',7,'Franchise and License'),
	('Guyana',2020,'KFC',7,'Franchise and License'),
	('Nepal',2020,'KFC',7,'Franchise and License'),
	('Lithuania',2022,'KFC',7,'Franchise and License'),
	('Sudan',2022,'KFC',7,'Franchise and License'),
	('Suriname',2022,'KFC',7,'Franchise and License'),
	('Zambia',2022,'KFC',7,'Franchise and License'),
	('Lithuania',2023,'KFC',7,'Franchise and License'),
	('Sudan',2023,'KFC',7,'Franchise and License'),
	('Suriname',2023,'KFC',7,'Franchise and License'),
	('Zambia',2023,'KFC',7,'Franchise and License'),
	('Bolivia',2018,'Pizza Hut',7,'Franchise and License'),
	('Czech Republic',2018,'Pizza Hut',7,'Franchise and License'),
	('Ghana',2018,'Pizza Hut',7,'Franchise and License'),
	('Iraq',2018,'Pizza Hut',7,'Franchise and License'),
	('Mauritius',2018,'Pizza Hut',7,'Franchise and License'),
	('Myanmar',2018,'Pizza Hut',7,'Franchise and License'),
	('Bolivia',2019,'Pizza Hut',7,'Franchise and License'),
	('Guyana',2019,'Pizza Hut',7,'Franchise and License'),
	('Iraq',2019,'Pizza Hut',7,'Franchise and License'),
	('Mauritius',2019,'Pizza Hut',7,'Franchise and License'),
	('Bolivia',2020,'Pizza Hut',7,'Franchise and License'),
	('Guyana',2020,'Pizza Hut',7,'Franchise and License'),
	('Mauritius',2020,'Pizza Hut',7,'Franchise and License'),
	('Switzerland',2020,'Pizza Hut',7,'Franchise and License'),
	('Armenia',2021,'Pizza Hut',7,'Franchise and License'),
	('Ghana',2021,'Pizza Hut',7,'Franchise and License'),
	('Nigeria',2021,'Pizza Hut',7,'Franchise and License'),
	('Switzerland',2021,'Pizza Hut',7,'Franchise and License'),
	('Armenia',2022,'Pizza Hut',7,'Franchise and License'),
	('Cambodia',2022,'Pizza Hut',7,'Franchise and License'),
	('Armenia',2023,'Pizza Hut',7,'Franchise and License'),
	('Azerbaijan',2023,'Pizza Hut',7,'Franchise and License'),
	('Bolivia',2023,'Pizza Hut',7,'Franchise and License'),
	('Cambodia',2023,'Pizza Hut',7,'Franchise and License'),
	('Lebanon',2023,'Pizza Hut',7,'Franchise and License'),
	('Guam',2018,'Taco Bell',7,'Franchise and License'),
	('Kuwait',2018,'Taco Bell',7,'Franchise and License'),
	('China',2019,'Taco Bell',7,'Franchise and License'),
	('El Salvador',2019,'Taco Bell',7,'Franchise and License'),
	('Guam',2019,'Taco Bell',7,'Franchise and License'),
	('Philippines',2019,'Taco Bell',7,'Franchise and License'),
	('Guam',2020,'Taco Bell',7,'Franchise and License'),
	('El Salvador',2021,'Taco Bell',7,'Franchise and License'),
	('Guam',2021,'Taco Bell',7,'Franchise and License'),
	('Guam',2022,'Taco Bell',7,'Franchise and License'),
	('Guam',2023,'Taco Bell',7,'Franchise and License'),
	('China',2020,'Habit',7,'Franchise and License'),
	('China',2021,'Habit',7,'Franchise and License'),
	('Cambodia',2023,'Habit',7,'Franchise and License'),
	('Croatia',2018,'KFC',8,'Franchise and License'),
	('Greece',2018,'KFC',8,'Franchise and License'),
	('Guam',2018,'KFC',8,'Franchise and License'),
	('Iceland',2018,'KFC',8,'Franchise and License'),
	('Iraq',2018,'KFC',8,'Franchise and License'),
	('Serbia',2018,'KFC',8,'Franchise and License'),
	('Sweden',2018,'KFC',8,'Franchise and License'),
	('Uganda',2018,'KFC',8,'Franchise and License'),
	('Austria',2019,'KFC',8,'Franchise and License'),
	('Croatia',2019,'KFC',8,'Franchise and License'),
	('El Salvador',2019,'KFC',8,'Franchise and License'),
	('Guam',2019,'KFC',8,'Franchise and License'),
	('Iceland',2019,'KFC',8,'Franchise and License'),
	('Iraq',2019,'KFC',8,'Franchise and License'),
	('Lesotho',2019,'KFC',8,'Franchise and License'),
	('Swaziland',2019,'KFC',8,'Franchise and License'),
	('Sweden',2019,'KFC',8,'Franchise and License'),
	('Austria',2020,'KFC',8,'Franchise and License'),
	('Croatia',2020,'KFC',8,'Franchise and License'),
	('Georgia',2020,'KFC',8,'Franchise and License'),
	('Greece',2020,'KFC',8,'Franchise and License'),
	('Guam',2020,'KFC',8,'Franchise and License'),
	('Iceland',2020,'KFC',8,'Franchise and License'),
	('Iraq',2020,'KFC',8,'Franchise and License'),
	('Kyrgyzstan',2020,'KFC',8,'Franchise and License'),
	('Lesotho',2020,'KFC',8,'Franchise and License'),
	('Switzerland',2020,'KFC',8,'Franchise and License'),
	('Tunisia',2020,'KFC',8,'Franchise and License'),
	('Albania',2021,'KFC',8,'Franchise and License'),
	('Croatia',2021,'KFC',8,'Franchise and License'),
	('Estonia',2021,'KFC',8,'Franchise and License'),
	('Guam',2021,'KFC',8,'Franchise and License'),
	('Iceland',2021,'KFC',8,'Franchise and License'),
	('Iraq',2021,'KFC',8,'Franchise and License'),
	('Israel',2021,'KFC',8,'Franchise and License'),
	('Albania',2022,'KFC',8,'Franchise and License'),
	('Croatia',2022,'KFC',8,'Franchise and License'),
	('Guam',2022,'KFC',8,'Franchise and License'),
	('Iceland',2022,'KFC',8,'Franchise and License'),
	('Iraq',2022,'KFC',8,'Franchise and License'),
	('Slovakia',2022,'KFC',8,'Franchise and License'),
	('Tanzania',2022,'KFC',8,'Franchise and License'),
	('Croatia',2023,'KFC',8,'Franchise and License'),
	('Guam',2023,'KFC',8,'Franchise and License'),
	('Iceland',2023,'KFC',8,'Franchise and License'),
	('Tanzania',2023,'KFC',8,'Franchise and License'),
	('Military - MENA',2018,'Pizza Hut',8,'Franchise and License'),
	('Switzerland',2018,'Pizza Hut',8,'Franchise and License'),
	('Macau',2019,'Pizza Hut',8,'Franchise and License'),
	('Military - MENA',2019,'Pizza Hut',8,'Franchise and License'),
	('Switzerland',2019,'Pizza Hut',8,'Franchise and License'),
	('Tanzania',2019,'Pizza Hut',8,'Franchise and License'),
	('West Bank',2019,'Pizza Hut',8,'Franchise and License'),
	('Ghana',2020,'Pizza Hut',8,'Franchise and License'),
	('Macau',2020,'Pizza Hut',8,'Franchise and License'),
	('Tanzania',2020,'Pizza Hut',8,'Franchise and License'),
	('West Bank',2020,'Pizza Hut',8,'Franchise and License'),
	('Macau',2021,'Pizza Hut',8,'Franchise and License'),
	('Tanzania',2021,'Pizza Hut',8,'Franchise and License'),
	('West Bank',2021,'Pizza Hut',8,'Franchise and License'),
	('Macau',2022,'Pizza Hut',8,'Franchise and License'),
	('Nigeria',2022,'Pizza Hut',8,'Franchise and License'),
	('Macau',2023,'Pizza Hut',8,'Franchise and License'),
	('Military - Europe',2023,'Pizza Hut',8,'Franchise and License'),
	('Japan',2018,'Taco Bell',8,'Franchise and License'),
	('Philippines',2018,'Taco Bell',8,'Franchise and License'),
	('Philippines',2020,'Taco Bell',8,'Franchise and License'),
	('Thailand',2020,'Taco Bell',8,'Franchise and License'),
	('South Korea',2021,'Taco Bell',8,'Franchise and License'),
	('South Korea',2022,'Taco Bell',8,'Franchise and License'),
	('Indonesia',2023,'Taco Bell',8,'Franchise and License'),
	('Japan',2023,'Taco Bell',8,'Franchise and License'),
	('Netherlands',2023,'Taco Bell',8,'Franchise and License'),
	('Angola',2018,'KFC',9,'Franchise and License'),
	('Armenia',2018,'KFC',9,'Franchise and License'),
	('Azerbaijan',2018,'KFC',9,'Franchise and License'),
	('Kosovo',2018,'KFC',9,'Franchise and License'),
	('Angola',2019,'KFC',9,'Franchise and License'),
	('Greece',2019,'KFC',9,'Franchise and License'),
	('Angola',2020,'KFC',9,'Franchise and License'),
	('El Salvador',2020,'KFC',9,'Franchise and License'),
	('Uzbekistan',2020,'KFC',9,'Franchise and License'),
	('Angola',2021,'KFC',9,'Franchise and License'),
	('Georgia',2021,'KFC',9,'Franchise and License'),
	('Guatemala',2021,'KFC',9,'Franchise and License'),
	('Guyana',2021,'KFC',9,'Franchise and License'),
	('Lesotho',2021,'KFC',9,'Franchise and License'),
	('Angola',2022,'KFC',9,'Franchise and License'),
	('Estonia',2022,'KFC',9,'Franchise and License'),
	('Guyana',2022,'KFC',9,'Franchise and License'),
	('Albania',2023,'KFC',9,'Franchise and License'),
	('Angola',2023,'KFC',9,'Franchise and License'),
	('Estonia',2023,'KFC',9,'Franchise and License'),
	('Guyana',2023,'KFC',9,'Franchise and License'),
	('Luxembourg',2018,'Pizza Hut',9,'Franchise and License'),
	('Military - Europe',2018,'Pizza Hut',9,'Franchise and License'),
	('Venezuela',2018,'Pizza Hut',9,'Franchise and License'),
	('Luxembourg',2019,'Pizza Hut',9,'Franchise and License'),
	('Venezuela',2019,'Pizza Hut',9,'Franchise and License'),
	('Military - Europe',2020,'Pizza Hut',9,'Franchise and License'),
	('Venezuela',2020,'Pizza Hut',9,'Franchise and License'),
	('Guyana',2021,'Pizza Hut',9,'Franchise and License'),
	('Military - Europe',2021,'Pizza Hut',9,'Franchise and License'),
	('Venezuela',2021,'Pizza Hut',9,'Franchise and License'),
	('Military - Europe',2022,'Pizza Hut',9,'Franchise and License'),
	('Tanzania',2022,'Pizza Hut',9,'Franchise and License'),
	('Venezuela',2022,'Pizza Hut',9,'Franchise and License'),
	('Tanzania',2023,'Pizza Hut',9,'Franchise and License'),
	('Venezuela',2023,'Pizza Hut',9,'Franchise and License'),
	('Chile',2018,'Taco Bell',9,'Franchise and License'),
	('Chile',2019,'Taco Bell',9,'Franchise and License'),
	('Kuwait',2019,'Taco Bell',9,'Franchise and License'),
	('Kuwait',2020,'Taco Bell',9,'Franchise and License'),
	('El Salvador',2022,'Taco Bell',9,'Franchise and License'),
	('Japan',2022,'Taco Bell',9,'Franchise and License'),
	('Sri Lanka',2022,'Taco Bell',9,'Franchise and License'),
	('El Salvador',2023,'Taco Bell',9,'Franchise and License'),
	('Sri Lanka',2023,'Taco Bell',9,'Franchise and License'),
	('Argentina',2018,'KFC',10,'Franchise and License'),
	('Denmark',2018,'KFC',10,'Franchise and License'),
	('West Bank',2018,'KFC',10,'Franchise and License'),
	('Armenia',2019,'KFC',10,'Franchise and License'),
	('Serbia',2019,'KFC',10,'Franchise and License'),
	('Armenia',2020,'KFC',10,'Franchise and License'),
	('Swaziland',2020,'KFC',10,'Franchise and License'),
	('Belgium',2021,'KFC',10,'Franchise and License'),
	('El Salvador',2021,'KFC',10,'Franchise and License'),
	('Kyrgyzstan',2021,'KFC',10,'Franchise and License'),
	('Tunisia',2021,'KFC',10,'Franchise and License'),
	('Lesotho',2022,'KFC',10,'Franchise and License'),
	('Tunisia',2022,'KFC',10,'Franchise and License'),
	('Zimbabwe',2022,'KFC',10,'Franchise and License'),
	('Iraq',2023,'KFC',10,'Franchise and License'),
	('Lesotho',2023,'KFC',10,'Franchise and License'),
	('Tunisia',2023,'KFC',10,'Franchise and License'),
	('Zimbabwe',2023,'KFC',10,'Franchise and License'),
	('Trinidad and Tobago',2018,'Pizza Hut',10,'Franchise and License'),
	('Ghana',2019,'Pizza Hut',10,'Franchise and License'),
	('Military - Europe',2019,'Pizza Hut',10,'Franchise and License'),
	('Luxembourg',2020,'Pizza Hut',10,'Franchise and License'),
	('Luxembourg',2021,'Pizza Hut',10,'Franchise and License'),
	('Guyana',2022,'Pizza Hut',10,'Franchise and License'),
	('Luxembourg',2022,'Pizza Hut',10,'Franchise and License'),
	('West Bank',2022,'Pizza Hut',10,'Franchise and License'),
	('Guyana',2023,'Pizza Hut',10,'Franchise and License'),
	('Luxembourg',2023,'Pizza Hut',10,'Franchise and License'),
	('West Bank',2023,'Pizza Hut',10,'Franchise and License'),
	('Finland',2019,'Taco Bell',10,'Franchise and License'),
	('Romania',2019,'Taco Bell',10,'Franchise and License'),
	('Finland',2020,'Taco Bell',10,'Franchise and License'),
	('New Zealand',2021,'Taco Bell',10,'Franchise and License'),
	('Philippines',2021,'Taco Bell',10,'Franchise and License'),
	('Philippines',2022,'Taco Bell',10,'Franchise and License'),
	('Cambodia',2018,'KFC',11,'Franchise and License'),
	('Azerbaijan',2019,'KFC',11,'Franchise and License'),
	('Denmark',2019,'KFC',11,'Franchise and License'),
	('Kosovo',2019,'KFC',11,'Franchise and License'),
	('Uganda',2019,'KFC',11,'Franchise and License'),
	('Barbados',2020,'KFC',11,'Franchise and License'),
	('Armenia',2021,'KFC',11,'Franchise and License'),
	('Austria',2021,'KFC',11,'Franchise and License'),
	('Barbados',2021,'KFC',11,'Franchise and License'),
	('Swaziland',2021,'KFC',11,'Franchise and License'),
	('Switzerland',2021,'KFC',11,'Franchise and License'),
	('Barbados',2022,'KFC',11,'Franchise and License'),
	('Georgia',2022,'KFC',11,'Franchise and License'),
	('Guatemala',2022,'KFC',11,'Franchise and License'),
	('Mozambique',2022,'KFC',11,'Franchise and License'),
	('Swaziland',2022,'KFC',11,'Franchise and License'),
	('Barbados',2023,'KFC',11,'Franchise and License'),
	('Guatemala',2023,'KFC',11,'Franchise and License'),
	('Mozambique',2023,'KFC',11,'Franchise and License'),
	('Slovakia',2023,'KFC',11,'Franchise and License'),
	('Swaziland',2023,'KFC',11,'Franchise and License'),
	('Jamaica',2018,'Pizza Hut',11,'Franchise and License'),
	('Myanmar',2019,'Pizza Hut',11,'Franchise and License'),
	('Nigeria',2023,'Pizza Hut',11,'Franchise and License'),
	('Panama',2018,'Taco Bell',11,'Franchise and License'),
	('Panama',2019,'Taco Bell',11,'Franchise and License'),
	('Romania',2020,'Taco Bell',11,'Franchise and License'),
	('Kuwait',2021,'Taco Bell',11,'Franchise and License'),
	('Panama',2021,'Taco Bell',11,'Franchise and License'),
	('Portugal',2021,'Taco Bell',11,'Franchise and License'),
	('Thailand',2021,'Taco Bell',11,'Franchise and License'),
	('South Korea',2023,'Taco Bell',11,'Franchise and License'),
	('Philippines',2023,'Taco Bell',11,'Franchise and License'),
	('Barbados',2018,'KFC',12,'Franchise and License'),
	('Botswana',2018,'KFC',12,'Franchise and License'),
	('Mongolia',2018,'KFC',12,'Franchise and License'),
	('Bahamas',2019,'KFC',12,'Franchise and License'),
	('Barbados',2019,'KFC',12,'Franchise and License'),
	('Cambodia',2019,'KFC',12,'Franchise and License'),
	('Mongolia',2019,'KFC',12,'Franchise and License'),
	('Mozambique',2019,'KFC',12,'Franchise and License'),
	('Bahamas',2020,'KFC',12,'Franchise and License'),
	('Denmark',2020,'KFC',12,'Franchise and License'),
	('Kosovo',2020,'KFC',12,'Franchise and License'),
	('Mongolia',2020,'KFC',12,'Franchise and License'),
	('Mozambique',2020,'KFC',12,'Franchise and License'),
	('Serbia',2020,'KFC',12,'Franchise and License'),
	('Sweden',2020,'KFC',12,'Franchise and License'),
	('Uganda',2020,'KFC',12,'Franchise and License'),
	('Bahamas',2021,'KFC',12,'Franchise and License'),
	('Cambodia',2021,'KFC',12,'Franchise and License'),
	('Denmark',2021,'KFC',12,'Franchise and License'),
	('Greece',2021,'KFC',12,'Franchise and License'),
	('Mozambique',2021,'KFC',12,'Franchise and License'),
	('Sweden',2021,'KFC',12,'Franchise and License'),
	('Uganda',2021,'KFC',12,'Franchise and License'),
	('Armenia',2022,'KFC',12,'Franchise and License'),
	('Austria',2022,'KFC',12,'Franchise and License'),
	('Denmark',2022,'KFC',12,'Franchise and License'),
	('El Salvador',2022,'KFC',12,'Franchise and License'),
	('Switzerland',2022,'KFC',12,'Franchise and License'),
	('Denmark',2023,'KFC',12,'Franchise and License'),
	('Finland',2018,'Pizza Hut',12,'Franchise and License'),
	('Trinidad and Tobago',2019,'Pizza Hut',12,'Franchise and License'),
	('Panama',2020,'Pizza Hut',12,'Franchise and License'),
	('Trinidad and Tobago',2020,'Pizza Hut',12,'Franchise and License'),
	('Myanmar',2021,'Pizza Hut',12,'Franchise and License'),
	('Panama',2021,'Pizza Hut',12,'Franchise and License'),
	('Trinidad and Tobago',2021,'Pizza Hut',12,'Franchise and License'),
	('Myanmar',2022,'Pizza Hut',12,'Franchise and License'),
	('Trinidad and Tobago',2022,'Pizza Hut',12,'Franchise and License'),
	('Myanmar',2023,'Pizza Hut',12,'Franchise and License'),
	('Trinidad and Tobago',2023,'Pizza Hut',12,'Franchise and License'),
	('Japan',2019,'Taco Bell',12,'Franchise and License'),
	('China',2020,'Taco Bell',12,'Franchise and License'),
	('Japan',2020,'Taco Bell',12,'Franchise and License'),
	('Panama',2020,'Taco Bell',12,'Franchise and License'),
	('Japan',2021,'Taco Bell',12,'Franchise and License'),
	('Kuwait',2022,'Taco Bell',12,'Franchise and License'),
	('Thailand',2022,'Taco Bell',12,'Franchise and License'),
	('Bahamas',2018,'KFC',13,'Franchise and License'),
	('West Bank',2019,'KFC',13,'Franchise and License'),
	('Azerbaijan',2020,'KFC',13,'Franchise and License'),
	('Cambodia',2020,'KFC',13,'Franchise and License'),
	('West Bank',2020,'KFC',13,'Franchise and License'),
	('Kosovo',2021,'KFC',13,'Franchise and License'),
	('Nepal',2021,'KFC',13,'Franchise and License'),
	('Serbia',2021,'KFC',13,'Franchise and License'),
	('Uzbekistan',2021,'KFC',13,'Franchise and License'),
	('Bahamas',2022,'KFC',13,'Franchise and License'),
	('Cambodia',2022,'KFC',13,'Franchise and License'),
	('Uganda',2022,'KFC',13,'Franchise and License'),
	('Austria',2023,'KFC',13,'Franchise and License'),
	('Bahamas',2023,'KFC',13,'Franchise and License'),
	('Cambodia',2023,'KFC',13,'Franchise and License'),
	('El Salvador',2023,'KFC',13,'Franchise and License'),
	('Georgia',2023,'KFC',13,'Franchise and License'),
	('Switzerland',2023,'KFC',13,'Franchise and License'),
	('Mongolia',2018,'Pizza Hut',13,'Franchise and License'),
	('Jamaica',2019,'Pizza Hut',13,'Franchise and License'),
	('Mongolia',2019,'Pizza Hut',13,'Franchise and License'),
	('Myanmar',2020,'Pizza Hut',13,'Franchise and License'),
	('Ghana',2022,'Pizza Hut',13,'Franchise and License'),
	('Australia',2019,'Taco Bell',13,'Franchise and License'),
	('Chile',2020,'Taco Bell',13,'Franchise and License'),
	('Romania',2021,'Taco Bell',13,'Franchise and License'),
	('New Zealand',2022,'Taco Bell',13,'Franchise and License'),
	('Panama',2022,'Taco Bell',13,'Franchise and License'),
	('Kuwait',2023,'Taco Bell',13,'Franchise and License'),
	('Panama',2023,'Taco Bell',13,'Franchise and License'),
	('Mozambique',2018,'KFC',14,'Franchise and License'),
	('Mongolia',2021,'KFC',14,'Franchise and License'),
	('West Bank',2021,'KFC',14,'Franchise and License'),
	('Greece',2022,'KFC',14,'Franchise and License'),
	('Kyrgyzstan',2022,'KFC',14,'Franchise and License'),
	('Kosovo',2022,'KFC',14,'Franchise and License'),
	('Armenia',2023,'KFC',14,'Franchise and License'),
	('Kyrgyzstan',2023,'KFC',14,'Franchise and License'),
	('Uganda',2023,'KFC',14,'Franchise and License'),
	('Ireland',2020,'Pizza Hut',14,'Franchise and License'),
	('Jamaica',2020,'Pizza Hut',14,'Franchise and License'),
	('Mongolia',2020,'Pizza Hut',14,'Franchise and License'),
	('Ireland',2021,'Pizza Hut',14,'Franchise and License'),
	('Jamaica',2021,'Pizza Hut',14,'Franchise and License'),
	('Ireland',2022,'Pizza Hut',14,'Franchise and License'),
	('Ghana',2023,'Pizza Hut',14,'Franchise and License'),
	('Ireland',2023,'Pizza Hut',14,'Franchise and License'),
	('Military - Europe',2018,'Taco Bell',14,'Franchise and License'),
	('Military - Europe',2019,'Taco Bell',14,'Franchise and License'),
	('Military - Europe',2020,'Taco Bell',14,'Franchise and License'),
	('Military - Europe',2021,'Taco Bell',14,'Franchise and License'),
	('Military - Europe',2022,'Taco Bell',14,'Franchise and License'),
	('Military - Europe',2023,'Taco Bell',14,'Franchise and License'),
	('New Zealand',2023,'Taco Bell',14,'Franchise and License'),
	('Honduras',2018,'KFC',15,'Franchise and License'),
	('Botswana',2019,'KFC',15,'Franchise and License'),
	('Honduras',2019,'KFC',15,'Franchise and License'),
	('Honduras',2020,'KFC',15,'Franchise and License'),
	('Belgium',2022,'KFC',15,'Franchise and License'),
	('Israel',2022,'KFC',15,'Franchise and License'),
	('Mongolia',2022,'KFC',15,'Franchise and License'),
	('Nepal',2022,'KFC',15,'Franchise and License'),
	('Serbia',2022,'KFC',15,'Franchise and License'),
	('Sweden',2022,'KFC',15,'Franchise and License'),
	('Belgium',2023,'KFC',15,'Franchise and License'),
	('Greece',2023,'KFC',15,'Franchise and License'),
	('Kosovo',2023,'KFC',15,'Franchise and License'),
	('Serbia',2023,'KFC',15,'Franchise and License'),
	('Brunei',2018,'Pizza Hut',15,'Franchise and License'),
	('Brunei',2019,'Pizza Hut',15,'Franchise and License'),
	('Lebanon',2019,'Pizza Hut',15,'Franchise and License'),
	('Jamaica',2022,'Pizza Hut',15,'Franchise and License'),
	('Jamaica',2023,'Pizza Hut',15,'Franchise and License'),
	('South Korea',2018,'Taco Bell',15,'Franchise and License'),
	('South Korea',2019,'Taco Bell',15,'Franchise and License'),
	('South Korea',2020,'Taco Bell',15,'Franchise and License'),
	('Finland',2021,'Taco Bell',15,'Franchise and License'),
	('Romania',2022,'Taco Bell',15,'Franchise and License'),
	('Romania',2023,'Taco Bell',15,'Franchise and License'),
	('Belarus',2018,'KFC',16,'Franchise and License'),
	('Brunei',2018,'KFC',16,'Franchise and License'),
	('Botswana',2020,'KFC',16,'Franchise and License'),
	('Uzbekistan',2022,'KFC',16,'Franchise and License'),
	('Israel',2023,'KFC',16,'Franchise and License'),
	('Nepal',2023,'KFC',16,'Franchise and License'),
	('Sweden',2023,'KFC',16,'Franchise and License'),
	('Bahrain',2018,'Pizza Hut',16,'Franchise and License'),
	('Bangladesh',2018,'Pizza Hut',16,'Franchise and License'),
	('Greece',2018,'Pizza Hut',16,'Franchise and License'),
	('Bahrain',2019,'Pizza Hut',16,'Franchise and License'),
	('Greece',2019,'Pizza Hut',16,'Franchise and License'),
	('Bangladesh',2020,'Pizza Hut',16,'Franchise and License'),
	('Brunei',2020,'Pizza Hut',16,'Franchise and License'),
	('Czech Republic',2022,'Pizza Hut',16,'Franchise and License'),
	('Czech Republic',2023,'Pizza Hut',16,'Franchise and License'),
	('Dominican Republic',2018,'Taco Bell',16,'Franchise and License'),
	('Dominican Republic',2019,'Taco Bell',16,'Franchise and License'),
	('Dominican Republic',2020,'Taco Bell',16,'Franchise and License'),
	('Dominican Republic',2021,'Taco Bell',16,'Franchise and License'),
	('Finland',2022,'Taco Bell',16,'Franchise and License'),
	('Portugal',2022,'Taco Bell',16,'Franchise and License'),
	('Finland',2023,'Taco Bell',16,'Franchise and License'),
	('Portugal',2023,'Taco Bell',16,'Franchise and License'),
	('Ghana',2018,'KFC',17,'Franchise and License'),
	('Morocco',2018,'KFC',17,'Franchise and License'),
	('Morocco',2019,'KFC',17,'Franchise and License'),
	('Azerbaijan',2021,'KFC',17,'Franchise and License'),
	('West Bank',2022,'KFC',17,'Franchise and License'),
	('Mongolia',2023,'KFC',17,'Franchise and License'),
	('Uzbekistan',2023,'KFC',17,'Franchise and License'),
	('West Bank',2023,'KFC',17,'Franchise and License'),
	('Nicaragua',2018,'Pizza Hut',17,'Franchise and License'),
	('Bangladesh',2019,'Pizza Hut',17,'Franchise and License'),
	('Czech Republic',2019,'Pizza Hut',17,'Franchise and License'),
	('Jordan',2019,'Pizza Hut',17,'Franchise and License'),
	('Nicaragua',2019,'Pizza Hut',17,'Franchise and License'),
	('Bahrain',2020,'Pizza Hut',17,'Franchise and License'),
	('Czech Republic',2020,'Pizza Hut',17,'Franchise and License'),
	('Jordan',2020,'Pizza Hut',17,'Franchise and License'),
	('Nicaragua',2020,'Pizza Hut',17,'Franchise and License'),
	('Brunei',2021,'Pizza Hut',17,'Franchise and License'),
	('Czech Republic',2021,'Pizza Hut',17,'Franchise and License'),
	('Nicaragua',2021,'Pizza Hut',17,'Franchise and License'),
	('Nicaragua',2022,'Pizza Hut',17,'Franchise and License'),
	('Nicaragua',2023,'Pizza Hut',17,'Franchise and License'),
	('Australia',2020,'Taco Bell',17,'Franchise and License'),
	('Chile',2021,'Taco Bell',17,'Franchise and License'),
	('Dominican Republic',2022,'Taco Bell',17,'Franchise and License'),
	('Ukraine',2018,'KFC',18,'Franchise and License'),
	('Brunei',2019,'KFC',18,'Franchise and License'),
	('Brunei',2020,'KFC',18,'Franchise and License'),
	('Morocco',2020,'KFC',18,'Franchise and License'),
	('Botswana',2021,'KFC',18,'Franchise and License'),
	('Brunei',2021,'KFC',18,'Franchise and License'),
	('Brunei',2022,'KFC',18,'Franchise and License'),
	('Lebanon',2022,'KFC',18,'Franchise and License'),
	('Botswana',2023,'KFC',18,'Franchise and License'),
	('Brunei',2023,'KFC',18,'Franchise and License'),
	('Lebanon',2023,'KFC',18,'Franchise and License'),
	('Jordan',2018,'Pizza Hut',18,'Franchise and License'),
	('Finland',2019,'Pizza Hut',18,'Franchise and License'),
	('Jordan',2021,'Pizza Hut',18,'Franchise and License'),
	('Mongolia',2021,'Pizza Hut',18,'Franchise and License'),
	('Brunei',2022,'Pizza Hut',18,'Franchise and License'),
	('Thailand',2023,'Taco Bell',18,'Franchise and License'),
	('Argentina',2019,'KFC',19,'Franchise and License'),
	('Argentina',2020,'KFC',19,'Franchise and License'),
	('Ghana',2020,'KFC',19,'Franchise and License'),
	('Lebanon',2020,'KFC',19,'Franchise and License'),
	('Honduras',2021,'KFC',19,'Franchise and License'),
	('Lebanon',2021,'KFC',19,'Franchise and License'),
	('Namibia',2021,'KFC',19,'Franchise and License'),
	('Botswana',2022,'KFC',19,'Franchise and License'),
	('Hungary',2018,'Pizza Hut',19,'Franchise and License'),
	('Military - United States',2018,'Pizza Hut',19,'Franchise and License'),
	('Finland',2020,'Pizza Hut',19,'Franchise and License'),
	('Military - United States',2020,'Pizza Hut',19,'Franchise and License'),
	('Bangladesh',2021,'Pizza Hut',19,'Franchise and License'),
	('Military - United States',2021,'Pizza Hut',19,'Franchise and License'),
	('Jordan',2022,'Pizza Hut',19,'Franchise and License'),
	('Military - United States',2022,'Pizza Hut',19,'Franchise and License'),
	('Brunei',2023,'Pizza Hut',19,'Franchise and License'),
	('Military - United States',2023,'Pizza Hut',19,'Franchise and License'),
	('Dominican Republic',2023,'Taco Bell',19,'Franchise and License'),
	('Argentina',2021,'KFC',20,'Franchise and License'),
	('Morocco',2021,'KFC',20,'Franchise and License'),
	('Lebanon',2018,'Pizza Hut',20,'Franchise and License'),
	('Ireland',2019,'Pizza Hut',20,'Franchise and License'),
	('Military - United States',2019,'Pizza Hut',20,'Franchise and License'),
	('Mongolia',2022,'Pizza Hut',20,'Franchise and License'),
	('Jordan',2023,'Pizza Hut',20,'Franchise and License'),
	('Malaysia',2022,'Taco Bell',20,'Franchise and License'),
	('Military - Asia',2022,'Taco Bell',20,'Franchise and License'),
	('Chile',2023,'Taco Bell',20,'Franchise and License'),
	('Military - Asia',2023,'Taco Bell',20,'Franchise and License'),
	('Bangladesh',2018,'KFC',21,'Franchise and License'),
	('Kenya',2018,'KFC',21,'Franchise and License'),
	('Mauritius',2018,'KFC',21,'Franchise and License'),
	('Namibia',2018,'KFC',21,'Franchise and License'),
	('Nigeria',2018,'KFC',21,'Franchise and License'),
	('Ghana',2019,'KFC',21,'Franchise and License'),
('Mauritius',2019,'KFC',21,'Franchise and License')

