




insert into 
	yum.Restaurant_Income
values 

	(2018,'KFC','Revenues','Company sales','Q1',245),
	(2018,'KFC','Revenues','Franchise and property revenues','Q1',307),
	(2018,'KFC','Revenues','Franchise contributions for advertising and other services','Q1',106),
	(2018,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q1',220),
	(2018,'KFC','Costs and Expenses, Net','General and administrative expenses','Q1',85),
	(2018,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q1',29),
	(2018,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',104),
	(2018,'KFC','Costs and Expenses, Net','Other (income) expense','Q1',-1),
	(2018,'Pizza Hut','Revenues','Company sales','Q1',24),
	(2018,'Pizza Hut','Revenues','Franchise and property revenues','Q1',149),
	(2018,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q1',78),
	(2018,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q1',24),
	(2018,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q1',50),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q1',11),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',78),
	(2018,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2018,'Taco Bell','Revenues','Company sales','Q1',243),
	(2018,'Taco Bell','Revenues','Franchise and property revenues','Q1',128),
	(2018,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q1',91),
	(2018,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q1',194),
	(2018,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q1',40),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q1',6),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',90),
	(2018,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2019,'KFC','Revenues','Company sales','Q1',125),
	(2019,'KFC','Revenues','Franchise and property revenues','Q1',323),
	(2019,'KFC','Revenues','Franchise contributions for advertising and other services','Q1',118),
	(2019,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q1',108),
	(2019,'KFC','Costs and Expenses, Net','General and administrative expenses','Q1',78),
	(2019,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q1',28),
	(2019,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',116),
	(2019,'KFC','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2019,'Pizza Hut','Revenues','Company sales','Q1',11),
	(2019,'Pizza Hut','Revenues','Franchise and property revenues','Q1',145),
	(2019,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q1',87),
	(2019,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q1',11),
	(2019,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q1',47),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q1',5),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',83),
	(2019,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2019,'Taco Bell','Revenues','Company sales','Q1',197),
	(2019,'Taco Bell','Revenues','Franchise and property revenues','Q1',144),
	(2019,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q1',104),
	(2019,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q1',153),
	(2019,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q1',43),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q1',9),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',102),
	(2019,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2020,'KFC','Revenues','Company sales','Q1',130),
	(2020,'KFC','Revenues','Franchise and property revenues','Q1',315),
	(2020,'KFC','Revenues','Franchise contributions for advertising and other services','Q1',121),
	(2020,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q1',115),
	(2020,'KFC','Costs and Expenses, Net','General and administrative expenses','Q1',73),
	(2020,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q1',33),
	(2020,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',120),
	(2020,'KFC','Costs and Expenses, Net','Other (income) expense','Q1',1),
	(2020,'Pizza Hut','Revenues','Company sales','Q1',18),
	(2020,'Pizza Hut','Revenues','Franchise and property revenues','Q1',133),
	(2020,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q1',84),
	(2020,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q1',19),
	(2020,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q1',46),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q1',12),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',84),
	(2020,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q1',-2),
	(2020,'Taco Bell','Revenues','Company sales','Q1',198),
	(2020,'Taco Bell','Revenues','Franchise and property revenues','Q1',148),
	(2020,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q1',107),
	(2020,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q1',153),
	(2020,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q1',38),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q1',11),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',106),
	(2020,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q1',1),
	(2021,'KFC','Revenues','Company sales','Q1',133),
	(2021,'KFC','Revenues','Franchise and property revenues','Q1',354),
	(2021,'KFC','Revenues','Franchise contributions for advertising and other services','Q1',138),
	(2021,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q1',111),
	(2021,'KFC','Costs and Expenses, Net','General and administrative expenses','Q1',73),
	(2021,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q1',14),
	(2021,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',133),
	(2021,'KFC','Costs and Expenses, Net','Other (income) expense','Q1',-6),
	(2021,'Pizza Hut','Revenues','Company sales','Q1',14),
	(2021,'Pizza Hut','Revenues','Franchise and property revenues','Q1',141),
	(2021,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q1',96),
	(2021,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q1',13),
	(2021,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q1',40),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q1',2),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',94),
	(2021,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2021,'Taco Bell','Revenues','Company sales','Q1',208),
	(2021,'Taco Bell','Revenues','Franchise and property revenues','Q1',162),
	(2021,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q1',118),
	(2021,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q1',158),
	(2021,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q1',31),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q1',7),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',116),
	(2021,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q1',-2),
	(2022,'KFC','Revenues','Company sales','Q1',126),
	(2022,'KFC','Revenues','Franchise and property revenues','Q1',383),
	(2022,'KFC','Revenues','Franchise contributions for advertising and other services','Q1',151),
	(2022,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q1',108),
	(2022,'KFC','Costs and Expenses, Net','General and administrative expenses','Q1',84),
	(2022,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q1',24),
	(2022,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',151),
	(2022,'KFC','Costs and Expenses, Net','Other (income) expense','Q1',2),
	(2022,'Pizza Hut','Revenues','Company sales','Q1',5),
	(2022,'Pizza Hut','Revenues','Franchise and property revenues','Q1',151),
	(2022,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q1',88),
	(2022,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q1',5),
	(2022,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q1',50),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q1',2),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',87),
	(2022,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q1',-2),
	(2022,'Taco Bell','Revenues','Company sales','Q1',214),
	(2022,'Taco Bell','Revenues','Franchise and property revenues','Q1',179),
	(2022,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q1',124),
	(2022,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q1',167),
	(2022,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q1',36),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q1',6),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',123),
	(2022,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q1',0),
	(2023,'KFC','Revenues','Company sales','Q1',110),
	(2023,'KFC','Revenues','Franchise and property revenues','Q1',412),
	(2023,'KFC','Revenues','Franchise contributions for advertising and other services','Q1',165),
	(2023,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q1',96),
	(2023,'KFC','Costs and Expenses, Net','General and administrative expenses','Q1',89),
	(2023,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q1',26),
	(2023,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',164),
	(2023,'KFC','Costs and Expenses, Net','Other (income) expense','Q1',7),
	(2023,'Pizza Hut','Revenues','Company sales','Q1',5),
	(2023,'Pizza Hut','Revenues','Franchise and property revenues','Q1',155),
	(2023,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q1',94),
	(2023,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q1',5),
	(2023,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q1',51),
	(2023,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q1',3),
	(2023,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',93),
	(2023,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q1',-2),
	(2023,'Taco Bell','Revenues','Company sales','Q1',229),
	(2023,'Taco Bell','Revenues','Franchise and property revenues','Q1',201),
	(2023,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q1',142),
	(2023,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q1',179),
	(2023,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q1',45),
	(2023,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q1',5),
	(2023,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q1',138),
	(2023,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q1',1),
	(2018,'KFC','Revenues','Company sales','Q2',241),
	(2018,'KFC','Revenues','Franchise and property revenues','Q2',310),
	(2018,'KFC','Revenues','Franchise contributions for advertising and other services','Q2',100),
	(2018,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q2',210),
	(2018,'KFC','Costs and Expenses, Net','General and administrative expenses','Q2',81),
	(2018,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q2',25),
	(2018,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',101),
	(2018,'KFC','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2018,'Pizza Hut','Revenues','Company sales','Q2',18),
	(2018,'Pizza Hut','Revenues','Franchise and property revenues','Q2',140),
	(2018,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q2',75),
	(2018,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q2',19),
	(2018,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q2',46),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q2',8),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',77),
	(2018,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q2',2),
	(2018,'Taco Bell','Revenues','Company sales','Q2',253),
	(2018,'Taco Bell','Revenues','Franchise and property revenues','Q2',134),
	(2018,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q2',97),
	(2018,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q2',193),
	(2018,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q2',41),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q2',6),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',96),
	(2018,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2019,'KFC','Revenues','Company sales','Q2',135),
	(2019,'KFC','Revenues','Franchise and property revenues','Q2',332),
	(2019,'KFC','Revenues','Franchise contributions for advertising and other services','Q2',117),
	(2019,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q2',113),
	(2019,'KFC','Costs and Expenses, Net','General and administrative expenses','Q2',75),
	(2019,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q2',19),
	(2019,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',116),
	(2019,'KFC','Costs and Expenses, Net','Other (income) expense','Q2',0),
	(2019,'Pizza Hut','Revenues','Company sales','Q2',11),
	(2019,'Pizza Hut','Revenues','Franchise and property revenues','Q2',143),
	(2019,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q2',92),
	(2019,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q2',10),
	(2019,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q2',44),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q2',9),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',89),
	(2019,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q2',-2),
	(2019,'Taco Bell','Revenues','Company sales','Q2',213),
	(2019,'Taco Bell','Revenues','Franchise and property revenues','Q2',158),
	(2019,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q2',109),
	(2019,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q2',163),
	(2019,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q2',41),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q2',8),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',110),
	(2019,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2020,'KFC','Revenues','Company sales','Q2',86),
	(2020,'KFC','Revenues','Franchise and property revenues','Q2',251),
	(2020,'KFC','Revenues','Franchise contributions for advertising and other services','Q2',72),
	(2020,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q2',83),
	(2020,'KFC','Costs and Expenses, Net','General and administrative expenses','Q2',70),
	(2020,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q2',29),
	(2020,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',70),
	(2020,'KFC','Costs and Expenses, Net','Other (income) expense','Q2',4),
	(2020,'Pizza Hut','Revenues','Company sales','Q2',19),
	(2020,'Pizza Hut','Revenues','Franchise and property revenues','Q2',126),
	(2020,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q2',90),
	(2020,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q2',18),
	(2020,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q2',44),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q2',1),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',87),
	(2020,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q2',-2),
	(2020,'Taco Bell','Revenues','Company sales','Q2',194),
	(2020,'Taco Bell','Revenues','Franchise and property revenues','Q2',147),
	(2020,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q2',108),
	(2020,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q2',147),
	(2020,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q2',37),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q2',5),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',107),
	(2020,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2021,'KFC','Revenues','Company sales','Q2',147),
	(2021,'KFC','Revenues','Franchise and property revenues','Q2',379),
	(2021,'KFC','Revenues','Franchise contributions for advertising and other services','Q2',156),
	(2021,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q2',118),
	(2021,'KFC','Costs and Expenses, Net','General and administrative expenses','Q2',80),
	(2021,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q2',15),
	(2021,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',151),
	(2021,'KFC','Costs and Expenses, Net','Other (income) expense','Q2',0),
	(2021,'Pizza Hut','Revenues','Company sales','Q2',12),
	(2021,'Pizza Hut','Revenues','Franchise and property revenues','Q2',147),
	(2021,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q2',90),
	(2021,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q2',11),
	(2021,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q2',43),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q2',5),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',91),
	(2021,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q2',-4),
	(2021,'Taco Bell','Revenues','Company sales','Q2',223),
	(2021,'Taco Bell','Revenues','Franchise and property revenues','Q2',179),
	(2021,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q2',130),
	(2021,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q2',165),
	(2021,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q2',33),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q2',7),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',130),
	(2021,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2022,'KFC','Revenues','Company sales','Q2',115),
	(2022,'KFC','Revenues','Franchise and property revenues','Q2',394),
	(2022,'KFC','Revenues','Franchise contributions for advertising and other services','Q2',168),
	(2022,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q2',102),
	(2022,'KFC','Costs and Expenses, Net','General and administrative expenses','Q2',89),
	(2022,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q2',14),
	(2022,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',163),
	(2022,'KFC','Costs and Expenses, Net','Other (income) expense','Q2',16),
	(2022,'Pizza Hut','Revenues','Company sales','Q2',5),
	(2022,'Pizza Hut','Revenues','Franchise and property revenues','Q2',142),
	(2022,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q2',88),
	(2022,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q2',5),
	(2022,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q2',50),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q2',2),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',88),
	(2022,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q2',-3),
	(2022,'Taco Bell','Revenues','Company sales','Q2',243),
	(2022,'Taco Bell','Revenues','Franchise and property revenues','Q2',199),
	(2022,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q2',144),
	(2022,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q2',181),
	(2022,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q2',39),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q2',8),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',144),
	(2022,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2023,'KFC','Revenues','Company sales','Q2',115),
	(2023,'KFC','Revenues','Franchise and property revenues','Q2',416),
	(2023,'KFC','Revenues','Franchise contributions for advertising and other services','Q2',151),
	(2023,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q2',99),
	(2023,'KFC','Costs and Expenses, Net','General and administrative expenses','Q2',90),
	(2023,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q2',16),
	(2023,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',150),
	(2023,'KFC','Costs and Expenses, Net','Other (income) expense','Q2',1),
	(2023,'Pizza Hut','Revenues','Company sales','Q2',4),
	(2023,'Pizza Hut','Revenues','Franchise and property revenues','Q2',149),
	(2023,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q2',89),
	(2023,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q2',4),
	(2023,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q2',53),
	(2023,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q2',6),
	(2023,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',89),
	(2023,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q2',-1),
	(2023,'Taco Bell','Revenues','Company sales','Q2',253),
	(2023,'Taco Bell','Revenues','Franchise and property revenues','Q2',218),
	(2023,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q2',150),
	(2023,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q2',187),
	(2023,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q2',49),
	(2023,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q2',9),
	(2023,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q2',148),
	(2023,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q2',0),
	(2018,'KFC','Revenues','Company sales','Q3',221),
	(2018,'KFC','Revenues','Franchise and property revenues','Q3',320),
	(2018,'KFC','Revenues','Franchise contributions for advertising and other services','Q3',108),
	(2018,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q3',187),
	(2018,'KFC','Costs and Expenses, Net','General and administrative expenses','Q3',81),
	(2018,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q3',24),
	(2018,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',107),
	(2018,'KFC','Costs and Expenses, Net','Other (income) expense','Q3',2),
	(2018,'Pizza Hut','Revenues','Company sales','Q3',13),
	(2018,'Pizza Hut','Revenues','Franchise and property revenues','Q3',143),
	(2018,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q3',73),
	(2018,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q3',13),
	(2018,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q3',45),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q3',9),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',74),
	(2018,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q3',0),
	(2018,'Taco Bell','Revenues','Company sales','Q3',265),
	(2018,'Taco Bell','Revenues','Franchise and property revenues','Q3',142),
	(2018,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q3',106),
	(2018,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q3',200),
	(2018,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q3',40),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q3',5),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',107),
	(2018,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q3',0),
	(2019,'KFC','Revenues','Company sales','Q3',135),
	(2019,'KFC','Revenues','Franchise and property revenues','Q3',344),
	(2019,'KFC','Revenues','Franchise contributions for advertising and other services','Q3',130),
	(2019,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q3',113),
	(2019,'KFC','Costs and Expenses, Net','General and administrative expenses','Q3',80),
	(2019,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q3',23),
	(2019,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',126),
	(2019,'KFC','Costs and Expenses, Net','Other (income) expense','Q3',-3),
	(2019,'Pizza Hut','Revenues','Company sales','Q3',13),
	(2019,'Pizza Hut','Revenues','Franchise and property revenues','Q3',143),
	(2019,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q3',85),
	(2019,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q3',13),
	(2019,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q3',47),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q3',9),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',86),
	(2019,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q3',0),
	(2019,'Taco Bell','Revenues','Company sales','Q3',216),
	(2019,'Taco Bell','Revenues','Franchise and property revenues','Q3',158),
	(2019,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q3',115),
	(2019,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q3',166),
	(2019,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q3',40),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q3',9),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',113),
	(2019,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q3',0),
	(2020,'KFC','Revenues','Company sales','Q3',130),
	(2020,'KFC','Revenues','Franchise and property revenues','Q3',340),
	(2020,'KFC','Revenues','Franchise contributions for advertising and other services','Q3',116),
	(2020,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q3',109),
	(2020,'KFC','Costs and Expenses, Net','General and administrative expenses','Q3',81),
	(2020,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q3',7),
	(2020,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',111),
	(2020,'KFC','Costs and Expenses, Net','Other (income) expense','Q3',0),
	(2020,'Pizza Hut','Revenues','Company sales','Q3',20),
	(2020,'Pizza Hut','Revenues','Franchise and property revenues','Q3',134),
	(2020,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q3',89),
	(2020,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q3',18),
	(2020,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q3',51),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q3',-2),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',85),
	(2020,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q3',2),
	(2020,'Taco Bell','Revenues','Company sales','Q3',218),
	(2020,'Taco Bell','Revenues','Franchise and property revenues','Q3',165),
	(2020,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q3',118),
	(2020,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q3',158),
	(2020,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q3',33),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q3',8),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',117),
	(2020,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q3',-1),
	(2021,'KFC','Revenues','Company sales','Q3',143),
	(2021,'KFC','Revenues','Franchise and property revenues','Q3',391),
	(2021,'KFC','Revenues','Franchise contributions for advertising and other services','Q3',158),
	(2021,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q3',117),
	(2021,'KFC','Costs and Expenses, Net','General and administrative expenses','Q3',86),
	(2021,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q3',20),
	(2021,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',154),
	(2021,'KFC','Costs and Expenses, Net','Other (income) expense','Q3',1),
	(2021,'Pizza Hut','Revenues','Company sales','Q3',13),
	(2021,'Pizza Hut','Revenues','Franchise and property revenues','Q3',147),
	(2021,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q3',87),
	(2021,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q3',12),
	(2021,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q3',45),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q3',2),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',90),
	(2021,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q3',-3),
	(2021,'Taco Bell','Revenues','Company sales','Q3',225),
	(2021,'Taco Bell','Revenues','Franchise and property revenues','Q3',177),
	(2021,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q3',132),
	(2021,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q3',172),
	(2021,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q3',40),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q3',9),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',131),
	(2021,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q3',-2),
	(2022,'KFC','Revenues','Company sales','Q3',112),
	(2022,'KFC','Revenues','Franchise and property revenues','Q3',418),
	(2022,'KFC','Revenues','Franchise contributions for advertising and other services','Q3',174),
	(2022,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q3',97),
	(2022,'KFC','Costs and Expenses, Net','General and administrative expenses','Q3',96),
	(2022,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q3',15),
	(2022,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',166),
	(2022,'KFC','Costs and Expenses, Net','Other (income) expense','Q3',26),
	(2022,'Pizza Hut','Revenues','Company sales','Q3',4),
	(2022,'Pizza Hut','Revenues','Franchise and property revenues','Q3',145),
	(2022,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q3',88),
	(2022,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q3',5),
	(2022,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q3',45),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q3',5),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',91),
	(2022,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q3',-1),
	(2022,'Taco Bell','Revenues','Company sales','Q3',234),
	(2022,'Taco Bell','Revenues','Franchise and property revenues','Q3',196),
	(2022,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q3',138),
	(2022,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q3',177),
	(2022,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q3',41),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q3',8),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',139),
	(2022,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q3',-1),
	(2023,'KFC','Revenues','Company sales','Q3',117),
	(2023,'KFC','Revenues','Franchise and property revenues','Q3',426),
	(2023,'KFC','Revenues','Franchise contributions for advertising and other services','Q3',157),
	(2023,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q3',100),
	(2023,'KFC','Costs and Expenses, Net','General and administrative expenses','Q3',86),
	(2023,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q3',15),
	(2023,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',156),
	(2023,'KFC','Costs and Expenses, Net','Other (income) expense','Q3',-1),
	(2023,'Pizza Hut','Revenues','Company sales','Q3',2),
	(2023,'Pizza Hut','Revenues','Franchise and property revenues','Q3',150),
	(2023,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q3',90),
	(2023,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q3',2),
	(2023,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q3',51),
	(2023,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q3',5),
	(2023,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',91),
	(2023,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q3',-4),
	(2023,'Taco Bell','Revenues','Company sales','Q3',256),
	(2023,'Taco Bell','Revenues','Franchise and property revenues','Q3',218),
	(2023,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q3',155),
	(2023,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q3',195),
	(2023,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q3',47),
	(2023,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q3',7),
	(2023,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q3',153),
	(2023,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q3',1),
	(2018,'KFC','Revenues','Company sales','Q4',187),
	(2018,'KFC','Revenues','Franchise and property revenues','Q4',357),
	(2018,'KFC','Revenues','Franchise contributions for advertising and other services','Q4',142),
	(2018,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q4',158),
	(2018,'KFC','Costs and Expenses, Net','General and administrative expenses','Q4',103),
	(2018,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q4',29),
	(2018,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',140),
	(2018,'KFC','Costs and Expenses, Net','Other (income) expense','Q4',1),
	(2018,'Pizza Hut','Revenues','Company sales','Q4',14),
	(2018,'Pizza Hut','Revenues','Franchise and property revenues','Q4',166),
	(2018,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q4',95),
	(2018,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q4',13),
	(2018,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q4',56),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q4',17),
	(2018,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',99),
	(2018,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q4',-1),
	(2018,'Taco Bell','Revenues','Company sales','Q4',276),
	(2018,'Taco Bell','Revenues','Franchise and property revenues','Q4',186),
	(2018,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q4',135),
	(2018,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q4',206),
	(2018,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q4',56),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q4',11),
	(2018,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',135),
	(2018,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q4',-2),
	(2019,'KFC','Revenues','Company sales','Q4',176),
	(2019,'KFC','Revenues','Franchise and property revenues','Q4',391),
	(2019,'KFC','Revenues','Franchise contributions for advertising and other services','Q4',165),
	(2019,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q4',150),
	(2019,'KFC','Costs and Expenses, Net','General and administrative expenses','Q4',113),
	(2019,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q4',19),
	(2019,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',162),
	(2019,'KFC','Costs and Expenses, Net','Other (income) expense','Q4',3),
	(2019,'Pizza Hut','Revenues','Company sales','Q4',19),
	(2019,'Pizza Hut','Revenues','Franchise and property revenues','Q4',166),
	(2019,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q4',112),
	(2019,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q4',17),
	(2019,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q4',64),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q4',16),
	(2019,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',109),
	(2019,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q4',1),
	(2019,'Taco Bell','Revenues','Company sales','Q4',295),
	(2019,'Taco Bell','Revenues','Franchise and property revenues','Q4',213),
	(2019,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q4',157),
	(2019,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q4',218),
	(2019,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q4',57),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q4',12),
	(2019,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',156),
	(2019,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q4',-3),
	(2020,'KFC','Revenues','Company sales','Q4',160),
	(2020,'KFC','Revenues','Franchise and property revenues','Q4',389),
	(2020,'KFC','Revenues','Franchise contributions for advertising and other services','Q4',162),
	(2020,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q4',132),
	(2020,'KFC','Costs and Expenses, Net','General and administrative expenses','Q4',122),
	(2020,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q4',22),
	(2020,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',164),
	(2020,'KFC','Costs and Expenses, Net','Other (income) expense','Q4',4),
	(2020,'Pizza Hut','Revenues','Company sales','Q4',19),
	(2020,'Pizza Hut','Revenues','Franchise and property revenues','Q4',159),
	(2020,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q4',111),
	(2020,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q4',18),
	(2020,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q4',74),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q4',6),
	(2020,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',109),
	(2020,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q4',-1),
	(2020,'Taco Bell','Revenues','Company sales','Q4',272),
	(2020,'Taco Bell','Revenues','Franchise and property revenues','Q4',202),
	(2020,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q4',154),
	(2020,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q4',199),
	(2020,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q4',50),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q4',9),
	(2020,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',154),
	(2020,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q4',4),
	(2021,'KFC','Revenues','Company sales','Q4',173),
	(2021,'KFC','Revenues','Franchise and property revenues','Q4',433),
	(2021,'KFC','Revenues','Franchise contributions for advertising and other services','Q4',188),
	(2021,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q4',144),
	(2021,'KFC','Costs and Expenses, Net','General and administrative expenses','Q4',138),
	(2021,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q4',25),
	(2021,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',189),
	(2021,'KFC','Costs and Expenses, Net','Other (income) expense','Q4',0),
	(2021,'Pizza Hut','Revenues','Company sales','Q4',7),
	(2021,'Pizza Hut','Revenues','Franchise and property revenues','Q4',162),
	(2021,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q4',112),
	(2021,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q4',7),
	(2021,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q4',73),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q4',2),
	(2021,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',120),
	(2021,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q4',-2),
	(2021,'Taco Bell','Revenues','Company sales','Q4',288),
	(2021,'Taco Bell','Revenues','Franchise and property revenues','Q4',224),
	(2021,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q4',172),
	(2021,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q4',224),
	(2021,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q4',70),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q4',10),
	(2021,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',176),
	(2021,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q4',6),
	(2022,'KFC','Revenues','Company sales','Q4',138),
	(2022,'KFC','Revenues','Franchise and property revenues','Q4',450),
	(2022,'KFC','Revenues','Franchise contributions for advertising and other services','Q4',205),
	(2022,'KFC','Costs and Expenses, Net','Company restaurant expenses','Q4',119),
	(2022,'KFC','Costs and Expenses, Net','General and administrative expenses','Q4',121),
	(2022,'KFC','Costs and Expenses, Net','Franchise and property expenses','Q4',16),
	(2022,'KFC','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',204),
	(2022,'KFC','Costs and Expenses, Net','Other (income) expense','Q4',23),
	(2022,'Pizza Hut','Revenues','Company sales','Q4',7),
	(2022,'Pizza Hut','Revenues','Franchise and property revenues','Q4',169),
	(2022,'Pizza Hut','Revenues','Franchise contributions for advertising and other services','Q4',112),
	(2022,'Pizza Hut','Costs and Expenses, Net','Company restaurant expenses','Q4',6),
	(2022,'Pizza Hut','Costs and Expenses, Net','General and administrative expenses','Q4',66),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise and property expenses','Q4',4),
	(2022,'Pizza Hut','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',116),
	(2022,'Pizza Hut','Costs and Expenses, Net','Other (income) expense','Q4',-4),
	(2022,'Taco Bell','Revenues','Company sales','Q4',311),
	(2022,'Taco Bell','Revenues','Franchise and property revenues','Q4',263),
	(2022,'Taco Bell','Revenues','Franchise contributions for advertising and other services','Q4',192),
	(2022,'Taco Bell','Costs and Expenses, Net','Company restaurant expenses','Q4',241),
	(2022,'Taco Bell','Costs and Expenses, Net','General and administrative expenses','Q4',75),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise and property expenses','Q4',11),
	(2022,'Taco Bell','Costs and Expenses, Net','Franchise advertising and other services expense','Q4',193),
	(2022,'Taco Bell','Costs and Expenses, Net','Other (income) expense','Q4',0)


