use Projects


select * from Projects.yum.Balance_Sheet


insert into 
	yum.Balance_Sheet 
values 
	(2018,'Assets','Current Assets','Cash and cash equivalents',292)
	(2018,'Assets','Current Assets','Accounts and notes receivable (net)',561),
	(2018,'Assets','Current Assets','Prepaid expenses and other current assets',354),
	(2018,'Assets','Current Assets','Advertising cooperative assets, restricted',0),
	(2018,'Assets','Non-Current Assets','Property, plant and equipment (net)',1237),
	(2018,'Assets','Non-Current Assets','Goodwill',525),
	(2018,'Assets','Non-Current Assets','Intangible assets (net)',242),
	(2018,'Assets','Non-Current Assets','Other assets',724),
	(2018,'Assets','Non-Current Assets','Deferred income taxes',195),
	(2018,'Liabilities','Current Liabilities','Accounts payable and other current liabilities',911),
	(2018,'Liabilities','Current Liabilities','Income taxes payable',69),
	(2018,'Liabilities','Current Liabilities','Short-term borrowings',321),
	(2018,'Liabilities','Current Liabilities','Advertising cooperative liabilities',0),
	(2018,'Liabilities','Non-Current Liabilities','Long-term debt',9751),
	(2018,'Liabilities','Non-Current Liabilities','Other liabilities and deferred credits',1004),
	(2018,'Equity','Shareholders’ Deficit','Accumulated deficit',-7592),
	(2018,'Equity','Shareholders’ Deficit','Accumulated other comprehensive loss',-334),
	(2019,'Assets','Current Assets','Cash and cash equivalents',605),
	(2019,'Assets','Current Assets','Accounts and notes receivable (net)',584),
	(2019,'Assets','Current Assets','Prepaid expenses and other current assets',338),
	(2019,'Assets','Current Assets','Advertising cooperative assets, restricted',0),
	(2019,'Assets','Non-Current Assets','Property, plant and equipment (net)',1170),
	(2019,'Assets','Non-Current Assets','Goodwill',530),
	(2019,'Assets','Non-Current Assets','Intangible assets (net)',244),
	(2019,'Assets','Non-Current Assets','Other assets',1313),
	(2019,'Assets','Non-Current Assets','Deferred income taxes',447),
	(2019,'Liabilities','Current Liabilities','Accounts payable and other current liabilities',960),
	(2019,'Liabilities','Current Liabilities','Income taxes payable',150),
	(2019,'Liabilities','Current Liabilities','Short-term borrowings',431),
	(2019,'Liabilities','Current Liabilities','Advertising cooperative liabilities',0),
	(2019,'Liabilities','Non-Current Liabilities','Long-term debt',10131),
	(2019,'Liabilities','Non-Current Liabilities','Other liabilities and deferred credits',1575),
	(2019,'Equity','Shareholders’ Deficit','Accumulated deficit',-7628),
	(2019,'Equity','Shareholders’ Deficit','Accumulated other comprehensive loss',-388),
	(2020,'Assets','Current Assets','Cash and cash equivalents',730),
	(2020,'Assets','Current Assets','Accounts and notes receivable (net)',534),
	(2020,'Assets','Current Assets','Prepaid expenses and other current assets',425),
	(2020,'Assets','Current Assets','Advertising cooperative assets, restricted',0),
	(2020,'Assets','Non-Current Assets','Property, plant and equipment (net)',1235),
	(2020,'Assets','Non-Current Assets','Goodwill',597),
	(2020,'Assets','Non-Current Assets','Intangible assets (net)',343),
	(2020,'Assets','Non-Current Assets','Other assets',1435),
	(2020,'Assets','Non-Current Assets','Deferred income taxes',553),
	(2020,'Liabilities','Current Liabilities','Accounts payable and other current liabilities',1189),
	(2020,'Liabilities','Current Liabilities','Income taxes payable',33),
	(2020,'Liabilities','Current Liabilities','Short-term borrowings',453),
	(2020,'Liabilities','Current Liabilities','Advertising cooperative liabilities',0),
	(2020,'Liabilities','Non-Current Liabilities','Long-term debt',10272),
	(2020,'Liabilities','Non-Current Liabilities','Other liabilities and deferred credits',1796),
	(2020,'Equity','Shareholders’ Deficit','Accumulated deficit',-7480),
	(2020,'Equity','Shareholders’ Deficit','Accumulated other comprehensive loss',-411),
	(2021,'Assets','Current Assets','Cash and cash equivalents',486),
	(2021,'Assets','Current Assets','Accounts and notes receivable (net)',596),
	(2021,'Assets','Current Assets','Prepaid expenses and other current assets',450),
	(2021,'Assets','Current Assets','Advertising cooperative assets, restricted',0),
	(2021,'Assets','Non-Current Assets','Property, plant and equipment (net)',1207),
	(2021,'Assets','Non-Current Assets','Goodwill',657),
	(2021,'Assets','Non-Current Assets','Intangible assets (net)',359),
	(2021,'Assets','Non-Current Assets','Other assets',1487),
	(2021,'Assets','Non-Current Assets','Deferred income taxes',2),
	(2021,'Liabilities','Current Liabilities','Accounts payable and other current liabilities',1334),
	(2021,'Liabilities','Current Liabilities','Income taxes payable',13),
	(2021,'Liabilities','Current Liabilities','Short-term borrowings',68),
	(2021,'Liabilities','Current Liabilities','Advertising cooperative liabilities',0),
	(2021,'Liabilities','Non-Current Liabilities','Long-term debt',11178),
	(2021,'Liabilities','Non-Current Liabilities','Other liabilities and deferred credits',1746),
	(2021,'Equity','Shareholders’ Deficit','Accumulated deficit',-8048),
	(2021,'Equity','Shareholders’ Deficit','Accumulated other comprehensive loss',-325),
	(2022,'Assets','Current Assets','Cash and cash equivalents',367),
	(2022,'Assets','Current Assets','Accounts and notes receivable (net)',648),
	(2022,'Assets','Current Assets','Prepaid expenses and other current assets',594),
	(2022,'Assets','Current Assets','Advertising cooperative assets, restricted',0),
	(2022,'Assets','Non-Current Assets','Property, plant and equipment (net)',1171),
	(2022,'Assets','Non-Current Assets','Goodwill',638),
	(2022,'Assets','Non-Current Assets','Intangible assets (net)',354),
	(2022,'Assets','Non-Current Assets','Other assets',1324),
	(2022,'Assets','Non-Current Assets','Deferred income taxes',750),
	(2022,'Liabilities','Current Liabilities','Accounts payable and other current liabilities',1251),
	(2022,'Liabilities','Current Liabilities','Income taxes payable',16),
	(2022,'Liabilities','Current Liabilities','Short-term borrowings',398),
	(2022,'Liabilities','Current Liabilities','Advertising cooperative liabilities',0),
	(2022,'Liabilities','Non-Current Liabilities','Long-term debt',11453),
	(2022,'Liabilities','Non-Current Liabilities','Other liabilities and deferred credits',1604),
	(2022,'Equity','Shareholders’ Deficit','Accumulated deficit',-8507),
	(2022,'Equity','Shareholders’ Deficit','Accumulated other comprehensive loss',-369),
	(2023,'Assets','Current Assets','Cash and cash equivalents',656),
	(2023,'Assets','Current Assets','Accounts and notes receivable (net)',647),
	(2023,'Assets','Current Assets','Prepaid expenses and other current assets',402),
	(2023,'Assets','Current Assets','Advertising cooperative assets, restricted',0),
	(2023,'Assets','Non-Current Assets','Property, plant and equipment (net)',1157),
	(2023,'Assets','Non-Current Assets','Goodwill',638),
	(2023,'Assets','Non-Current Assets','Intangible assets (net)',369),
	(2023,'Assets','Non-Current Assets','Other assets',1360),
	(2023,'Assets','Non-Current Assets','Deferred income taxes',842),
	(2023,'Liabilities','Current Liabilities','Accounts payable and other current liabilities',1119),
	(2023,'Liabilities','Current Liabilities','Income taxes payable',12),
	(2023,'Liabilities','Current Liabilities','Short-term borrowings',373),
	(2023,'Liabilities','Current Liabilities','Advertising cooperative liabilities',0),
	(2023,'Liabilities','Non-Current Liabilities','Long-term debt',11152),
	(2023,'Liabilities','Non-Current Liabilities','Other liabilities and deferred credits',1605),
	(2023,'Equity','Shareholders’ Deficit','Accumulated deficit',-7909),
	(2023,'Equity','Shareholders’ Deficit','Accumulated other comprehensive loss',-314)


