

insert into 
	yum.Country
values 
	('Albania','Europe'),
	('Algeria','Africa'),
	('Andorra','Europe'),
	('Angola','Africa'),
	('Antigua and Barbuda','North America'),
	('Argentina','South America'),
	('Armenia','Asia'),
	('Aruba','North America'),
	('Australia','Oceania'),
	('Austria','Europe'),
	('Azerbaijan','Asia'),
	('Bahamas','North America'),
	('Bahrain','Asia'),
	('Bangladesh','Asia'),
	('Barbados','North America'),
	('Belarus','Europe'),
	('Belgium','Europe'),
	('Bermuda','North America'),
	('Bolivia','South America'),
	('Bonaire','North America'),
	('Bosnia and Herzegovina','Europe'),
	('Botswana','Africa'),
	('Brazil','South America'),
	('Brunei','Asia'),
	('Bulgaria','Europe'),
	('Cambodia','Asia'),
	('Cameroon','Africa'),
	('Canada','North America'),
	('Chile','South America'),
	('China','Asia'),
	('Colombia','South America'),
	('Costa Rica','North America'),
	('Croatia','Europe'),
	('Curacao','North America'),
	('Cyprus','Asia'),
	('Czech Republic','Europe'),
	('Denmark','Europe'),
	('Djibouti','Africa'),
	('Dominica','North America'),
	('Dominican Republic','North America'),
	('Ecuador','South America'),
	('Egypt','Africa'),
	('El Salvador','North America'),
	('Estonia','Europe'),
	('Ethiopia','Africa'),
	('Finland','Europe'),
	('France','Europe'),
	('French Guiana','South America'),
	('Gabon','Africa'),
	('Georgia','Asia'),
	('Germany','Europe'),
	('Ghana','Africa'),
	('Gibraltar','Europe'),
	('Grand Cayman','North America'),
	('Greece','Europe'),
	('Grenada','North America'),
	('Guadeloupe','South America'),
	('Guam','Oceania'),
	('Guatemala','North America'),
	('Guyana','South America'),
	('Honduras','North America'),
	('Hong Kong','Asia'),
	('Hungary','Europe'),
	('Iceland','Europe'),
	('India','Asia'),
	('Indonesia','Asia'),
	('Iraq','Asia'),
	('Ireland','Europe'),
	('Israel','Asia'),
	('Italy','Europe'),
	('Côte d''Ivoire','Africa'),
	('Jamaica','North America'),
	('Japan','Asia'),
	('Jordan','Asia'),
	('Kazakhstan','Asia'),
	('Kenya','Africa'),
	('South Korea','Asia'),
	('Kosovo','Europe'),
	('Kuwait','Asia'),
	('Kyrgyzstan','Asia'),
	('Latvia','Europe'),
	('Lebanon','Asia'),
	('Lesotho','Africa'),
	('Lithuania','Europe'),
	('Luxembourg','Europe'),
	('Macau','Asia'),
	('North Macedonia','Europe'),
	('Madagascar','Africa'),
	('Malawi','Africa'),
	('Malaysia','Asia'),
	('Maldives','Asia'),
	('Malta','Europe'),
	('Martinique','South America'),
	('Mauritius','Africa'),
	('Mexico','North America'),
	('Military - Africa','Military'),
	('Military - Asia','Military'),
	('Military - Europe','Military'),
	('Military - Iberia','Military'),
	('Military - Latin America','Military'),
	('Military - MENA','Military'),
	('Military - United States','Military'),
	('Moldova','Europe'),
	('Mongolia','Asia'),
	('Morocco','Africa'),
	('Mozambique','Africa'),
	('Myanmar','Asia'),
	('Namibia','Africa'),
	('Nepal','Asia'),
	('Netherlands','Europe'),
	('New Zealand','Oceania'),
	('Nicaragua','North America'),
	('Nigeria','Africa'),
	('Norway','Europe'),
	('Oman','Asia'),
	('Pakistan','Asia'),
	('Panama','North America'),
	('Paraguay','South America'),
	('Peru','South America'),
	('Philippines','Asia'),
	('Poland','Europe'),
	('Portugal','Europe'),
	('Puerto Rico','North America'),
	('Qatar','Asia'),
	('Réunion','Africa'),
	('Romania','Europe'),
	('Russia','Europe/Asia'),
	('Rwanda','Africa'),
	('Saipan','Oceania'),
	('Saudi Arabia','Asia'),
	('Senegal','Africa'),
	('Serbia','Europe'),
	('Singapore','Asia'),
	('Slovakia','Europe'),
	('Slovenia','Europe'),
	('Somaliland','Africa'),
	('South Africa','Africa'),
	('Spain','Europe'),
	('Sri Lanka','Asia'),
	('Saint Kitts and Nevis','North America'),
	('Saint Lucia','North America'),
	('Saint Maarten','North America'),
	('Saint Vincent and the Grenadines','North America'),
	('Sudan','Africa'),
	('Suriname','South America'),
	('Swaziland','Africa'),
	('Sweden','Europe'),
	('Switzerland','Europe'),
	('Taiwan','Asia'),
	('Tajikistan','Asia'),
	('Tanzania','Africa'),
	('Thailand','Asia'),
	('Trinidad and Tobago','North America'),
	('Tunisia','Africa'),
	('Turkey','Europe/Asia'),
	('Uganda','Africa'),
	('United Kingdom','Europe'),
	('Ukraine','Europe'),
	('United Arab Emirates','Asia'),
	('United States','North America'),
	('US Virgin Islands','North America'),
	('Uzbekistan','Asia'),
	('Venezuela','South America'),
	('Vietnam','Asia'),
	('West Bank','Asia'),
	('Zambia','Africa'),
	('Zimbabwe','Africa')

